// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: notion.proto

package notion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Parent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "database_id", "page_id", "workspace"
	DatabaseId    string                 `protobuf:"bytes,2,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	PageId        string                 `protobuf:"bytes,3,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parent) Reset() {
	*x = Parent{}
	mi := &file_notion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parent) ProtoMessage() {}

func (x *Parent) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parent.ProtoReflect.Descriptor instead.
func (*Parent) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{0}
}

func (x *Parent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parent) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *Parent) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type NotionUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "person" or "bot"
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotionUser) Reset() {
	*x = NotionUser{}
	mi := &file_notion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotionUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotionUser) ProtoMessage() {}

func (x *NotionUser) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotionUser.ProtoReflect.Descriptor instead.
func (*NotionUser) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{1}
}

func (x *NotionUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotionUser) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotionUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotionUser) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *NotionUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type NotionTeam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotionTeam) Reset() {
	*x = NotionTeam{}
	mi := &file_notion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotionTeam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotionTeam) ProtoMessage() {}

func (x *NotionTeam) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotionTeam.ProtoReflect.Descriptor instead.
func (*NotionTeam) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{2}
}

func (x *NotionTeam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotionTeam) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotionTeam) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Page struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	CreatedTime    string                 `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	LastEditedTime string                 `protobuf:"bytes,4,opt,name=last_edited_time,json=lastEditedTime,proto3" json:"last_edited_time,omitempty"`
	Archived       bool                   `protobuf:"varint,5,opt,name=archived,proto3" json:"archived,omitempty"`
	Parent         *Parent                `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	Properties     *structpb.Struct       `protobuf:"bytes,7,opt,name=properties,proto3" json:"properties,omitempty"`
	Icon           string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Cover          string                 `protobuf:"bytes,9,opt,name=cover,proto3" json:"cover,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_notion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{3}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Page) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *Page) GetLastEditedTime() string {
	if x != nil {
		return x.LastEditedTime
	}
	return ""
}

func (x *Page) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Page) GetParent() *Parent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Page) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Page) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Page) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

type Block struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreatedTime    string                 `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	LastEditedTime string                 `protobuf:"bytes,4,opt,name=last_edited_time,json=lastEditedTime,proto3" json:"last_edited_time,omitempty"`
	HasChildren    bool                   `protobuf:"varint,5,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	Archived       bool                   `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	Data           *structpb.Struct       `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"` // Type-specific block data
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_notion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{4}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *Block) GetLastEditedTime() string {
	if x != nil {
		return x.LastEditedTime
	}
	return ""
}

func (x *Block) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *Block) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Block) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type Sort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Property      string                 `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	Direction     string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"` // "ascending" or "descending"
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // "created_time" or "last_edited_time"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sort) Reset() {
	*x = Sort{}
	mi := &file_notion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{5}
}

func (x *Sort) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *Sort) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Sort) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SearchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object         string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"` // "page" or "database"
	Url            string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ParentId       string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	LastEditedTime string                 `protobuf:"bytes,6,opt,name=last_edited_time,json=lastEditedTime,proto3" json:"last_edited_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_notion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResult) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *SearchResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *SearchResult) GetLastEditedTime() string {
	if x != nil {
		return x.LastEditedTime
	}
	return ""
}

type CommentEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DiscussionId  string                 `protobuf:"bytes,2,opt,name=discussion_id,json=discussionId,proto3" json:"discussion_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedTime   string                 `protobuf:"bytes,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	CreatedById   string                 `protobuf:"bytes,5,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"`
	RichText      string                 `protobuf:"bytes,6,opt,name=rich_text,json=richText,proto3" json:"rich_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentEntry) Reset() {
	*x = CommentEntry{}
	mi := &file_notion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentEntry) ProtoMessage() {}

func (x *CommentEntry) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentEntry.ProtoReflect.Descriptor instead.
func (*CommentEntry) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{7}
}

func (x *CommentEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentEntry) GetDiscussionId() string {
	if x != nil {
		return x.DiscussionId
	}
	return ""
}

func (x *CommentEntry) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CommentEntry) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *CommentEntry) GetCreatedById() string {
	if x != nil {
		return x.CreatedById
	}
	return ""
}

func (x *CommentEntry) GetRichText() string {
	if x != nil {
		return x.RichText
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	FilterObject  string                 `protobuf:"bytes,2,opt,name=filter_object,json=filterObject,proto3" json:"filter_object,omitempty"` // "page" or "database"
	Sort          *Sort                  `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartCursor   string                 `protobuf:"bytes,5,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_notion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{8}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetFilterObject() string {
	if x != nil {
		return x.FilterObject
	}
	return ""
}

func (x *SearchRequest) GetSort() *Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *SearchRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchRequest) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_notion_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{9}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SearchResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_notion_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{10}
}

func (x *GetPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type GetPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageResponse) Reset() {
	*x = GetPageResponse{}
	mi := &file_notion_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageResponse) ProtoMessage() {}

func (x *GetPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageResponse.ProtoReflect.Descriptor instead.
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{11}
}

func (x *GetPageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        *Parent                `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	Children      []*structpb.Struct     `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"` // Block content
	IconEmoji     string                 `protobuf:"bytes,4,opt,name=icon_emoji,json=iconEmoji,proto3" json:"icon_emoji,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_notion_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePageRequest) GetParent() *Parent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *CreatePageRequest) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *CreatePageRequest) GetChildren() []*structpb.Struct {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *CreatePageRequest) GetIconEmoji() string {
	if x != nil {
		return x.IconEmoji
	}
	return ""
}

func (x *CreatePageRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type CreatePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageResponse) Reset() {
	*x = CreatePageResponse{}
	mi := &file_notion_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageResponse) ProtoMessage() {}

func (x *CreatePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageResponse.ProtoReflect.Descriptor instead.
func (*CreatePageResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	IconEmoji     string                 `protobuf:"bytes,3,opt,name=icon_emoji,json=iconEmoji,proto3" json:"icon_emoji,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,4,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePageRequest) Reset() {
	*x = UpdatePageRequest{}
	mi := &file_notion_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePageRequest) ProtoMessage() {}

func (x *UpdatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePageRequest.ProtoReflect.Descriptor instead.
func (*UpdatePageRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *UpdatePageRequest) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *UpdatePageRequest) GetIconEmoji() string {
	if x != nil {
		return x.IconEmoji
	}
	return ""
}

func (x *UpdatePageRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type UpdatePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePageResponse) Reset() {
	*x = UpdatePageResponse{}
	mi := &file_notion_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePageResponse) ProtoMessage() {}

func (x *UpdatePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePageResponse.ProtoReflect.Descriptor instead.
func (*UpdatePageResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type MovePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Parent        *Parent                `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePageRequest) Reset() {
	*x = MovePageRequest{}
	mi := &file_notion_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePageRequest) ProtoMessage() {}

func (x *MovePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePageRequest.ProtoReflect.Descriptor instead.
func (*MovePageRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{16}
}

func (x *MovePageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *MovePageRequest) GetParent() *Parent {
	if x != nil {
		return x.Parent
	}
	return nil
}

type MovePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePageResponse) Reset() {
	*x = MovePageResponse{}
	mi := &file_notion_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePageResponse) ProtoMessage() {}

func (x *MovePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePageResponse.ProtoReflect.Descriptor instead.
func (*MovePageResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{17}
}

func (x *MovePageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type ArchivePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Archived      bool                   `protobuf:"varint,2,opt,name=archived,proto3" json:"archived,omitempty"` // true to archive, false to unarchive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePageRequest) Reset() {
	*x = ArchivePageRequest{}
	mi := &file_notion_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePageRequest) ProtoMessage() {}

func (x *ArchivePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePageRequest.ProtoReflect.Descriptor instead.
func (*ArchivePageRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{18}
}

func (x *ArchivePageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *ArchivePageRequest) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

type ArchivePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivePageResponse) Reset() {
	*x = ArchivePageResponse{}
	mi := &file_notion_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivePageResponse) ProtoMessage() {}

func (x *ArchivePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivePageResponse.ProtoReflect.Descriptor instead.
func (*ArchivePageResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{19}
}

func (x *ArchivePageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPageId  string                 `protobuf:"bytes,1,opt,name=parent_page_id,json=parentPageId,proto3" json:"parent_page_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"` // Database property schema
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_notion_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{20}
}

func (x *CreateDatabaseRequest) GetParentPageId() string {
	if x != nil {
		return x.ParentPageId
	}
	return ""
}

func (x *CreateDatabaseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDatabaseRequest) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,4,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_notion_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{21}
}

func (x *CreateDatabaseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateDatabaseResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateDatabaseResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDatabaseResponse) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type QueryDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatabaseId    string                 `protobuf:"bytes,1,opt,name=database_id,json=databaseId,proto3" json:"database_id,omitempty"`
	Filter        *structpb.Struct       `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Sorts         []*Sort                `protobuf:"bytes,3,rep,name=sorts,proto3" json:"sorts,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartCursor   string                 `protobuf:"bytes,5,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDatabaseRequest) Reset() {
	*x = QueryDatabaseRequest{}
	mi := &file_notion_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDatabaseRequest) ProtoMessage() {}

func (x *QueryDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDatabaseRequest.ProtoReflect.Descriptor instead.
func (*QueryDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{22}
}

func (x *QueryDatabaseRequest) GetDatabaseId() string {
	if x != nil {
		return x.DatabaseId
	}
	return ""
}

func (x *QueryDatabaseRequest) GetFilter() *structpb.Struct {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryDatabaseRequest) GetSorts() []*Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

func (x *QueryDatabaseRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryDatabaseRequest) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

type QueryDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Page                `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDatabaseResponse) Reset() {
	*x = QueryDatabaseResponse{}
	mi := &file_notion_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDatabaseResponse) ProtoMessage() {}

func (x *QueryDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDatabaseResponse.ProtoReflect.Descriptor instead.
func (*QueryDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{23}
}

func (x *QueryDatabaseResponse) GetResults() []*Page {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryDatabaseResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *QueryDatabaseResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetBlockChildrenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartCursor   string                 `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockChildrenRequest) Reset() {
	*x = GetBlockChildrenRequest{}
	mi := &file_notion_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockChildrenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockChildrenRequest) ProtoMessage() {}

func (x *GetBlockChildrenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockChildrenRequest.ProtoReflect.Descriptor instead.
func (*GetBlockChildrenRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{24}
}

func (x *GetBlockChildrenRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *GetBlockChildrenRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetBlockChildrenRequest) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

type GetBlockChildrenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Block               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockChildrenResponse) Reset() {
	*x = GetBlockChildrenResponse{}
	mi := &file_notion_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockChildrenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockChildrenResponse) ProtoMessage() {}

func (x *GetBlockChildrenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockChildrenResponse.ProtoReflect.Descriptor instead.
func (*GetBlockChildrenResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{25}
}

func (x *GetBlockChildrenResponse) GetResults() []*Block {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetBlockChildrenResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetBlockChildrenResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type AppendBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Children      []*structpb.Struct     `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBlocksRequest) Reset() {
	*x = AppendBlocksRequest{}
	mi := &file_notion_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBlocksRequest) ProtoMessage() {}

func (x *AppendBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBlocksRequest.ProtoReflect.Descriptor instead.
func (*AppendBlocksRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{26}
}

func (x *AppendBlocksRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *AppendBlocksRequest) GetChildren() []*structpb.Struct {
	if x != nil {
		return x.Children
	}
	return nil
}

type AppendBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*Block               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendBlocksResponse) Reset() {
	*x = AppendBlocksResponse{}
	mi := &file_notion_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendBlocksResponse) ProtoMessage() {}

func (x *AppendBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendBlocksResponse.ProtoReflect.Descriptor instead.
func (*AppendBlocksResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{27}
}

func (x *AppendBlocksResponse) GetResults() []*Block {
	if x != nil {
		return x.Results
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentPageId  string                 `protobuf:"bytes,1,opt,name=parent_page_id,json=parentPageId,proto3" json:"parent_page_id,omitempty"`
	DiscussionId  string                 `protobuf:"bytes,2,opt,name=discussion_id,json=discussionId,proto3" json:"discussion_id,omitempty"` // For threaded replies
	RichText      string                 `protobuf:"bytes,3,opt,name=rich_text,json=richText,proto3" json:"rich_text,omitempty"`             // Plain text content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_notion_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{28}
}

func (x *CreateCommentRequest) GetParentPageId() string {
	if x != nil {
		return x.ParentPageId
	}
	return ""
}

func (x *CreateCommentRequest) GetDiscussionId() string {
	if x != nil {
		return x.DiscussionId
	}
	return ""
}

func (x *CreateCommentRequest) GetRichText() string {
	if x != nil {
		return x.RichText
	}
	return ""
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *CommentEntry          `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_notion_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{29}
}

func (x *CreateCommentResponse) GetComment() *CommentEntry {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartCursor   string                 `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsRequest) Reset() {
	*x = GetCommentsRequest{}
	mi := &file_notion_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsRequest) ProtoMessage() {}

func (x *GetCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetCommentsRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{30}
}

func (x *GetCommentsRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *GetCommentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetCommentsRequest) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

type GetCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentEntry        `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentsResponse) Reset() {
	*x = GetCommentsResponse{}
	mi := &file_notion_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentsResponse) ProtoMessage() {}

func (x *GetCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetCommentsResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{31}
}

func (x *GetCommentsResponse) GetComments() []*CommentEntry {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetCommentsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetCommentsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartCursor   string                 `protobuf:"bytes,2,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_notion_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{32}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*NotionUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_notion_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{33}
}

func (x *ListUsersResponse) GetUsers() []*NotionUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListUsersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_notion_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{34}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *NotionUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_notion_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{35}
}

func (x *GetUserResponse) GetUser() *NotionUser {
	if x != nil {
		return x.User
	}
	return nil
}

type GetSelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelfRequest) Reset() {
	*x = GetSelfRequest{}
	mi := &file_notion_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelfRequest) ProtoMessage() {}

func (x *GetSelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelfRequest.ProtoReflect.Descriptor instead.
func (*GetSelfRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{36}
}

type GetSelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *NotionUser            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelfResponse) Reset() {
	*x = GetSelfResponse{}
	mi := &file_notion_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelfResponse) ProtoMessage() {}

func (x *GetSelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelfResponse.ProtoReflect.Descriptor instead.
func (*GetSelfResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{37}
}

func (x *GetSelfResponse) GetUser() *NotionUser {
	if x != nil {
		return x.User
	}
	return nil
}

type ListTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StartCursor   string                 `protobuf:"bytes,2,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsRequest) Reset() {
	*x = ListTeamsRequest{}
	mi := &file_notion_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsRequest) ProtoMessage() {}

func (x *ListTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsRequest.ProtoReflect.Descriptor instead.
func (*ListTeamsRequest) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{38}
}

func (x *ListTeamsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTeamsRequest) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

type ListTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teams         []*NotionTeam          `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeamsResponse) Reset() {
	*x = ListTeamsResponse{}
	mi := &file_notion_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeamsResponse) ProtoMessage() {}

func (x *ListTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notion_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeamsResponse.ProtoReflect.Descriptor instead.
func (*ListTeamsResponse) Descriptor() ([]byte, []int) {
	return file_notion_proto_rawDescGZIP(), []int{39}
}

func (x *ListTeamsResponse) GetTeams() []*NotionTeam {
	if x != nil {
		return x.Teams
	}
	return nil
}

func (x *ListTeamsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListTeamsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_notion_proto protoreflect.FileDescriptor

const file_notion_proto_rawDesc = "" +
	"\n" +
	"\fnotion.proto\x12\x18tucker.mcproto.notion.v1\x1a\x1cgoogle/protobuf/struct.proto\"V\n" +
	"\x06Parent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vdatabase_id\x18\x02 \x01(\tR\n" +
	"databaseId\x12\x17\n" +
	"\apage_id\x18\x03 \x01(\tR\x06pageId\"y\n" +
	"\n" +
	"NotionUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\"R\n" +
	"\n" +
	"NotionTeam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xae\x02\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12!\n" +
	"\fcreated_time\x18\x03 \x01(\tR\vcreatedTime\x12(\n" +
	"\x10last_edited_time\x18\x04 \x01(\tR\x0elastEditedTime\x12\x1a\n" +
	"\barchived\x18\x05 \x01(\bR\barchived\x128\n" +
	"\x06parent\x18\x06 \x01(\v2 .tucker.mcproto.notion.v1.ParentR\x06parent\x127\n" +
	"\n" +
	"properties\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x14\n" +
	"\x05cover\x18\t \x01(\tR\x05cover\"\xe4\x01\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fcreated_time\x18\x03 \x01(\tR\vcreatedTime\x12(\n" +
	"\x10last_edited_time\x18\x04 \x01(\tR\x0elastEditedTime\x12!\n" +
	"\fhas_children\x18\x05 \x01(\bR\vhasChildren\x12\x1a\n" +
	"\barchived\x18\x06 \x01(\bR\barchived\x12+\n" +
	"\x04data\x18\a \x01(\v2\x17.google.protobuf.StructR\x04data\"^\n" +
	"\x04Sort\x12\x1a\n" +
	"\bproperty\x18\x01 \x01(\tR\bproperty\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xa5\x01\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12(\n" +
	"\x10last_edited_time\x18\x06 \x01(\tR\x0elastEditedTime\"\xc4\x01\n" +
	"\fCommentEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdiscussion_id\x18\x02 \x01(\tR\fdiscussionId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12!\n" +
	"\fcreated_time\x18\x04 \x01(\tR\vcreatedTime\x12\"\n" +
	"\rcreated_by_id\x18\x05 \x01(\tR\vcreatedById\x12\x1b\n" +
	"\trich_text\x18\x06 \x01(\tR\brichText\"\xbe\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12#\n" +
	"\rfilter_object\x18\x02 \x01(\tR\ffilterObject\x122\n" +
	"\x04sort\x18\x03 \x01(\v2\x1e.tucker.mcproto.notion.v1.SortR\x04sort\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12!\n" +
	"\fstart_cursor\x18\x05 \x01(\tR\vstartCursor\"\x8e\x01\n" +
	"\x0eSearchResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.tucker.mcproto.notion.v1.SearchResultR\aresults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\")\n" +
	"\x0eGetPageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"E\n" +
	"\x0fGetPageResponse\x122\n" +
	"\x04page\x18\x01 \x01(\v2\x1e.tucker.mcproto.notion.v1.PageR\x04page\"\xf7\x01\n" +
	"\x11CreatePageRequest\x128\n" +
	"\x06parent\x18\x01 \x01(\v2 .tucker.mcproto.notion.v1.ParentR\x06parent\x127\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x123\n" +
	"\bchildren\x18\x03 \x03(\v2\x17.google.protobuf.StructR\bchildren\x12\x1d\n" +
	"\n" +
	"icon_emoji\x18\x04 \x01(\tR\ticonEmoji\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\"H\n" +
	"\x12CreatePageResponse\x122\n" +
	"\x04page\x18\x01 \x01(\v2\x1e.tucker.mcproto.notion.v1.PageR\x04page\"\xa1\x01\n" +
	"\x11UpdatePageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x127\n" +
	"\n" +
	"properties\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12\x1d\n" +
	"\n" +
	"icon_emoji\x18\x03 \x01(\tR\ticonEmoji\x12\x1b\n" +
	"\tcover_url\x18\x04 \x01(\tR\bcoverUrl\"H\n" +
	"\x12UpdatePageResponse\x122\n" +
	"\x04page\x18\x01 \x01(\v2\x1e.tucker.mcproto.notion.v1.PageR\x04page\"d\n" +
	"\x0fMovePageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x128\n" +
	"\x06parent\x18\x02 \x01(\v2 .tucker.mcproto.notion.v1.ParentR\x06parent\"F\n" +
	"\x10MovePageResponse\x122\n" +
	"\x04page\x18\x01 \x01(\v2\x1e.tucker.mcproto.notion.v1.PageR\x04page\"I\n" +
	"\x12ArchivePageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x1a\n" +
	"\barchived\x18\x02 \x01(\bR\barchived\"I\n" +
	"\x13ArchivePageResponse\x122\n" +
	"\x04page\x18\x01 \x01(\v2\x1e.tucker.mcproto.notion.v1.PageR\x04page\"\x8c\x01\n" +
	"\x15CreateDatabaseRequest\x12$\n" +
	"\x0eparent_page_id\x18\x01 \x01(\tR\fparentPageId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x127\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"\x89\x01\n" +
	"\x16CreateDatabaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x127\n" +
	"\n" +
	"properties\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"\xde\x01\n" +
	"\x14QueryDatabaseRequest\x12\x1f\n" +
	"\vdatabase_id\x18\x01 \x01(\tR\n" +
	"databaseId\x12/\n" +
	"\x06filter\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06filter\x124\n" +
	"\x05sorts\x18\x03 \x03(\v2\x1e.tucker.mcproto.notion.v1.SortR\x05sorts\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12!\n" +
	"\fstart_cursor\x18\x05 \x01(\tR\vstartCursor\"\x8d\x01\n" +
	"\x15QueryDatabaseResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.tucker.mcproto.notion.v1.PageR\aresults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"t\n" +
	"\x17GetBlockChildrenRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fstart_cursor\x18\x03 \x01(\tR\vstartCursor\"\x91\x01\n" +
	"\x18GetBlockChildrenResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.tucker.mcproto.notion.v1.BlockR\aresults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"e\n" +
	"\x13AppendBlocksRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x123\n" +
	"\bchildren\x18\x02 \x03(\v2\x17.google.protobuf.StructR\bchildren\"Q\n" +
	"\x14AppendBlocksResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.tucker.mcproto.notion.v1.BlockR\aresults\"~\n" +
	"\x14CreateCommentRequest\x12$\n" +
	"\x0eparent_page_id\x18\x01 \x01(\tR\fparentPageId\x12#\n" +
	"\rdiscussion_id\x18\x02 \x01(\tR\fdiscussionId\x12\x1b\n" +
	"\trich_text\x18\x03 \x01(\tR\brichText\"Y\n" +
	"\x15CreateCommentResponse\x12@\n" +
	"\acomment\x18\x01 \x01(\v2&.tucker.mcproto.notion.v1.CommentEntryR\acomment\"o\n" +
	"\x12GetCommentsRequest\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fstart_cursor\x18\x03 \x01(\tR\vstartCursor\"\x95\x01\n" +
	"\x13GetCommentsResponse\x12B\n" +
	"\bcomments\x18\x01 \x03(\v2&.tucker.mcproto.notion.v1.CommentEntryR\bcomments\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"R\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12!\n" +
	"\fstart_cursor\x18\x02 \x01(\tR\vstartCursor\"\x8b\x01\n" +
	"\x11ListUsersResponse\x12:\n" +
	"\x05users\x18\x01 \x03(\v2$.tucker.mcproto.notion.v1.NotionUserR\x05users\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"K\n" +
	"\x0fGetUserResponse\x128\n" +
	"\x04user\x18\x01 \x01(\v2$.tucker.mcproto.notion.v1.NotionUserR\x04user\"\x10\n" +
	"\x0eGetSelfRequest\"K\n" +
	"\x0fGetSelfResponse\x128\n" +
	"\x04user\x18\x01 \x01(\v2$.tucker.mcproto.notion.v1.NotionUserR\x04user\"R\n" +
	"\x10ListTeamsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12!\n" +
	"\fstart_cursor\x18\x02 \x01(\tR\vstartCursor\"\x8b\x01\n" +
	"\x11ListTeamsResponse\x12:\n" +
	"\x05teams\x18\x01 \x03(\v2$.tucker.mcproto.notion.v1.NotionTeamR\x05teams\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursorB.Z,github.com/misfitdev/proto-mcp/go/pkg/notionb\x06proto3"

var (
	file_notion_proto_rawDescOnce sync.Once
	file_notion_proto_rawDescData []byte
)

func file_notion_proto_rawDescGZIP() []byte {
	file_notion_proto_rawDescOnce.Do(func() {
		file_notion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notion_proto_rawDesc), len(file_notion_proto_rawDesc)))
	})
	return file_notion_proto_rawDescData
}

var file_notion_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_notion_proto_goTypes = []any{
	(*Parent)(nil),                   // 0: tucker.mcproto.notion.v1.Parent
	(*NotionUser)(nil),               // 1: tucker.mcproto.notion.v1.NotionUser
	(*NotionTeam)(nil),               // 2: tucker.mcproto.notion.v1.NotionTeam
	(*Page)(nil),                     // 3: tucker.mcproto.notion.v1.Page
	(*Block)(nil),                    // 4: tucker.mcproto.notion.v1.Block
	(*Sort)(nil),                     // 5: tucker.mcproto.notion.v1.Sort
	(*SearchResult)(nil),             // 6: tucker.mcproto.notion.v1.SearchResult
	(*CommentEntry)(nil),             // 7: tucker.mcproto.notion.v1.CommentEntry
	(*SearchRequest)(nil),            // 8: tucker.mcproto.notion.v1.SearchRequest
	(*SearchResponse)(nil),           // 9: tucker.mcproto.notion.v1.SearchResponse
	(*GetPageRequest)(nil),           // 10: tucker.mcproto.notion.v1.GetPageRequest
	(*GetPageResponse)(nil),          // 11: tucker.mcproto.notion.v1.GetPageResponse
	(*CreatePageRequest)(nil),        // 12: tucker.mcproto.notion.v1.CreatePageRequest
	(*CreatePageResponse)(nil),       // 13: tucker.mcproto.notion.v1.CreatePageResponse
	(*UpdatePageRequest)(nil),        // 14: tucker.mcproto.notion.v1.UpdatePageRequest
	(*UpdatePageResponse)(nil),       // 15: tucker.mcproto.notion.v1.UpdatePageResponse
	(*MovePageRequest)(nil),          // 16: tucker.mcproto.notion.v1.MovePageRequest
	(*MovePageResponse)(nil),         // 17: tucker.mcproto.notion.v1.MovePageResponse
	(*ArchivePageRequest)(nil),       // 18: tucker.mcproto.notion.v1.ArchivePageRequest
	(*ArchivePageResponse)(nil),      // 19: tucker.mcproto.notion.v1.ArchivePageResponse
	(*CreateDatabaseRequest)(nil),    // 20: tucker.mcproto.notion.v1.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),   // 21: tucker.mcproto.notion.v1.CreateDatabaseResponse
	(*QueryDatabaseRequest)(nil),     // 22: tucker.mcproto.notion.v1.QueryDatabaseRequest
	(*QueryDatabaseResponse)(nil),    // 23: tucker.mcproto.notion.v1.QueryDatabaseResponse
	(*GetBlockChildrenRequest)(nil),  // 24: tucker.mcproto.notion.v1.GetBlockChildrenRequest
	(*GetBlockChildrenResponse)(nil), // 25: tucker.mcproto.notion.v1.GetBlockChildrenResponse
	(*AppendBlocksRequest)(nil),      // 26: tucker.mcproto.notion.v1.AppendBlocksRequest
	(*AppendBlocksResponse)(nil),     // 27: tucker.mcproto.notion.v1.AppendBlocksResponse
	(*CreateCommentRequest)(nil),     // 28: tucker.mcproto.notion.v1.CreateCommentRequest
	(*CreateCommentResponse)(nil),    // 29: tucker.mcproto.notion.v1.CreateCommentResponse
	(*GetCommentsRequest)(nil),       // 30: tucker.mcproto.notion.v1.GetCommentsRequest
	(*GetCommentsResponse)(nil),      // 31: tucker.mcproto.notion.v1.GetCommentsResponse
	(*ListUsersRequest)(nil),         // 32: tucker.mcproto.notion.v1.ListUsersRequest
	(*ListUsersResponse)(nil),        // 33: tucker.mcproto.notion.v1.ListUsersResponse
	(*GetUserRequest)(nil),           // 34: tucker.mcproto.notion.v1.GetUserRequest
	(*GetUserResponse)(nil),          // 35: tucker.mcproto.notion.v1.GetUserResponse
	(*GetSelfRequest)(nil),           // 36: tucker.mcproto.notion.v1.GetSelfRequest
	(*GetSelfResponse)(nil),          // 37: tucker.mcproto.notion.v1.GetSelfResponse
	(*ListTeamsRequest)(nil),         // 38: tucker.mcproto.notion.v1.ListTeamsRequest
	(*ListTeamsResponse)(nil),        // 39: tucker.mcproto.notion.v1.ListTeamsResponse
	(*structpb.Struct)(nil),          // 40: google.protobuf.Struct
}
var file_notion_proto_depIdxs = []int32{
	0,  // 0: tucker.mcproto.notion.v1.Page.parent:type_name -> tucker.mcproto.notion.v1.Parent
	40, // 1: tucker.mcproto.notion.v1.Page.properties:type_name -> google.protobuf.Struct
	40, // 2: tucker.mcproto.notion.v1.Block.data:type_name -> google.protobuf.Struct
	5,  // 3: tucker.mcproto.notion.v1.SearchRequest.sort:type_name -> tucker.mcproto.notion.v1.Sort
	6,  // 4: tucker.mcproto.notion.v1.SearchResponse.results:type_name -> tucker.mcproto.notion.v1.SearchResult
	3,  // 5: tucker.mcproto.notion.v1.GetPageResponse.page:type_name -> tucker.mcproto.notion.v1.Page
	0,  // 6: tucker.mcproto.notion.v1.CreatePageRequest.parent:type_name -> tucker.mcproto.notion.v1.Parent
	40, // 7: tucker.mcproto.notion.v1.CreatePageRequest.properties:type_name -> google.protobuf.Struct
	40, // 8: tucker.mcproto.notion.v1.CreatePageRequest.children:type_name -> google.protobuf.Struct
	3,  // 9: tucker.mcproto.notion.v1.CreatePageResponse.page:type_name -> tucker.mcproto.notion.v1.Page
	40, // 10: tucker.mcproto.notion.v1.UpdatePageRequest.properties:type_name -> google.protobuf.Struct
	3,  // 11: tucker.mcproto.notion.v1.UpdatePageResponse.page:type_name -> tucker.mcproto.notion.v1.Page
	0,  // 12: tucker.mcproto.notion.v1.MovePageRequest.parent:type_name -> tucker.mcproto.notion.v1.Parent
	3,  // 13: tucker.mcproto.notion.v1.MovePageResponse.page:type_name -> tucker.mcproto.notion.v1.Page
	3,  // 14: tucker.mcproto.notion.v1.ArchivePageResponse.page:type_name -> tucker.mcproto.notion.v1.Page
	40, // 15: tucker.mcproto.notion.v1.CreateDatabaseRequest.properties:type_name -> google.protobuf.Struct
	40, // 16: tucker.mcproto.notion.v1.CreateDatabaseResponse.properties:type_name -> google.protobuf.Struct
	40, // 17: tucker.mcproto.notion.v1.QueryDatabaseRequest.filter:type_name -> google.protobuf.Struct
	5,  // 18: tucker.mcproto.notion.v1.QueryDatabaseRequest.sorts:type_name -> tucker.mcproto.notion.v1.Sort
	3,  // 19: tucker.mcproto.notion.v1.QueryDatabaseResponse.results:type_name -> tucker.mcproto.notion.v1.Page
	4,  // 20: tucker.mcproto.notion.v1.GetBlockChildrenResponse.results:type_name -> tucker.mcproto.notion.v1.Block
	40, // 21: tucker.mcproto.notion.v1.AppendBlocksRequest.children:type_name -> google.protobuf.Struct
	4,  // 22: tucker.mcproto.notion.v1.AppendBlocksResponse.results:type_name -> tucker.mcproto.notion.v1.Block
	7,  // 23: tucker.mcproto.notion.v1.CreateCommentResponse.comment:type_name -> tucker.mcproto.notion.v1.CommentEntry
	7,  // 24: tucker.mcproto.notion.v1.GetCommentsResponse.comments:type_name -> tucker.mcproto.notion.v1.CommentEntry
	1,  // 25: tucker.mcproto.notion.v1.ListUsersResponse.users:type_name -> tucker.mcproto.notion.v1.NotionUser
	1,  // 26: tucker.mcproto.notion.v1.GetUserResponse.user:type_name -> tucker.mcproto.notion.v1.NotionUser
	1,  // 27: tucker.mcproto.notion.v1.GetSelfResponse.user:type_name -> tucker.mcproto.notion.v1.NotionUser
	2,  // 28: tucker.mcproto.notion.v1.ListTeamsResponse.teams:type_name -> tucker.mcproto.notion.v1.NotionTeam
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_notion_proto_init() }
func file_notion_proto_init() {
	if File_notion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notion_proto_rawDesc), len(file_notion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_notion_proto_goTypes,
		DependencyIndexes: file_notion_proto_depIdxs,
		MessageInfos:      file_notion_proto_msgTypes,
	}.Build()
	File_notion_proto = out.File
	file_notion_proto_goTypes = nil
	file_notion_proto_depIdxs = nil
}
