// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: github.proto

package github

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitHubService_CreateRepository_FullMethodName        = "/tucker.mcproto.github.v1.GitHubService/CreateRepository"
	GitHubService_SearchRepositories_FullMethodName      = "/tucker.mcproto.github.v1.GitHubService/SearchRepositories"
	GitHubService_GetRepository_FullMethodName           = "/tucker.mcproto.github.v1.GitHubService/GetRepository"
	GitHubService_ForkRepository_FullMethodName          = "/tucker.mcproto.github.v1.GitHubService/ForkRepository"
	GitHubService_GetFileContents_FullMethodName         = "/tucker.mcproto.github.v1.GitHubService/GetFileContents"
	GitHubService_CreateOrUpdateFile_FullMethodName      = "/tucker.mcproto.github.v1.GitHubService/CreateOrUpdateFile"
	GitHubService_PushFiles_FullMethodName               = "/tucker.mcproto.github.v1.GitHubService/PushFiles"
	GitHubService_CreateBranch_FullMethodName            = "/tucker.mcproto.github.v1.GitHubService/CreateBranch"
	GitHubService_ListCommits_FullMethodName             = "/tucker.mcproto.github.v1.GitHubService/ListCommits"
	GitHubService_CreateIssue_FullMethodName             = "/tucker.mcproto.github.v1.GitHubService/CreateIssue"
	GitHubService_ListIssues_FullMethodName              = "/tucker.mcproto.github.v1.GitHubService/ListIssues"
	GitHubService_GetIssue_FullMethodName                = "/tucker.mcproto.github.v1.GitHubService/GetIssue"
	GitHubService_UpdateIssue_FullMethodName             = "/tucker.mcproto.github.v1.GitHubService/UpdateIssue"
	GitHubService_AddIssueComment_FullMethodName         = "/tucker.mcproto.github.v1.GitHubService/AddIssueComment"
	GitHubService_SearchIssues_FullMethodName            = "/tucker.mcproto.github.v1.GitHubService/SearchIssues"
	GitHubService_CreatePullRequest_FullMethodName       = "/tucker.mcproto.github.v1.GitHubService/CreatePullRequest"
	GitHubService_GetPullRequest_FullMethodName          = "/tucker.mcproto.github.v1.GitHubService/GetPullRequest"
	GitHubService_ListPullRequests_FullMethodName        = "/tucker.mcproto.github.v1.GitHubService/ListPullRequests"
	GitHubService_CreatePullRequestReview_FullMethodName = "/tucker.mcproto.github.v1.GitHubService/CreatePullRequestReview"
	GitHubService_MergePullRequest_FullMethodName        = "/tucker.mcproto.github.v1.GitHubService/MergePullRequest"
	GitHubService_GetPullRequestFiles_FullMethodName     = "/tucker.mcproto.github.v1.GitHubService/GetPullRequestFiles"
	GitHubService_GetPullRequestStatus_FullMethodName    = "/tucker.mcproto.github.v1.GitHubService/GetPullRequestStatus"
	GitHubService_UpdatePullRequestBranch_FullMethodName = "/tucker.mcproto.github.v1.GitHubService/UpdatePullRequestBranch"
	GitHubService_GetPullRequestComments_FullMethodName  = "/tucker.mcproto.github.v1.GitHubService/GetPullRequestComments"
	GitHubService_GetPullRequestReviews_FullMethodName   = "/tucker.mcproto.github.v1.GitHubService/GetPullRequestReviews"
	GitHubService_SearchCode_FullMethodName              = "/tucker.mcproto.github.v1.GitHubService/SearchCode"
	GitHubService_SearchUsers_FullMethodName             = "/tucker.mcproto.github.v1.GitHubService/SearchUsers"
)

// GitHubServiceClient is the client API for GitHubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for GitHub MCP
type GitHubServiceClient interface {
	// Repository Operations
	CreateRepository(ctx context.Context, in *CreateRepositoryRequest, opts ...grpc.CallOption) (*CreateRepositoryResponse, error)
	SearchRepositories(ctx context.Context, in *SearchRepositoriesRequest, opts ...grpc.CallOption) (*SearchRepositoriesResponse, error)
	GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*GetRepositoryResponse, error)
	ForkRepository(ctx context.Context, in *ForkRepositoryRequest, opts ...grpc.CallOption) (*ForkRepositoryResponse, error)
	// File Operations
	GetFileContents(ctx context.Context, in *GetFileContentsRequest, opts ...grpc.CallOption) (*GetFileContentsResponse, error)
	CreateOrUpdateFile(ctx context.Context, in *CreateOrUpdateFileRequest, opts ...grpc.CallOption) (*FileCommitResponse, error)
	PushFiles(ctx context.Context, in *PushFilesRequest, opts ...grpc.CallOption) (*PushFilesResponse, error)
	// Branch & Commit Operations
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error)
	ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	// Issue Operations
	CreateIssue(ctx context.Context, in *CreateIssueRequest, opts ...grpc.CallOption) (*CreateIssueResponse, error)
	ListIssues(ctx context.Context, in *ListIssuesRequest, opts ...grpc.CallOption) (*ListIssuesResponse, error)
	GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error)
	UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error)
	AddIssueComment(ctx context.Context, in *AddIssueCommentRequest, opts ...grpc.CallOption) (*AddIssueCommentResponse, error)
	SearchIssues(ctx context.Context, in *SearchIssuesRequest, opts ...grpc.CallOption) (*SearchIssuesResponse, error)
	// Pull Request Operations
	CreatePullRequest(ctx context.Context, in *CreatePullRequestRequest, opts ...grpc.CallOption) (*CreatePullRequestResponse, error)
	GetPullRequest(ctx context.Context, in *GetPullRequestRequest, opts ...grpc.CallOption) (*GetPullRequestResponse, error)
	ListPullRequests(ctx context.Context, in *ListPullRequestsRequest, opts ...grpc.CallOption) (*ListPullRequestsResponse, error)
	CreatePullRequestReview(ctx context.Context, in *CreatePullRequestReviewRequest, opts ...grpc.CallOption) (*CreatePullRequestReviewResponse, error)
	MergePullRequest(ctx context.Context, in *MergePullRequestRequest, opts ...grpc.CallOption) (*MergePullRequestResponse, error)
	GetPullRequestFiles(ctx context.Context, in *GetPullRequestFilesRequest, opts ...grpc.CallOption) (*GetPullRequestFilesResponse, error)
	GetPullRequestStatus(ctx context.Context, in *GetPullRequestStatusRequest, opts ...grpc.CallOption) (*GetPullRequestStatusResponse, error)
	UpdatePullRequestBranch(ctx context.Context, in *UpdatePullRequestBranchRequest, opts ...grpc.CallOption) (*UpdatePullRequestBranchResponse, error)
	GetPullRequestComments(ctx context.Context, in *GetPullRequestCommentsRequest, opts ...grpc.CallOption) (*GetPullRequestCommentsResponse, error)
	GetPullRequestReviews(ctx context.Context, in *GetPullRequestReviewsRequest, opts ...grpc.CallOption) (*GetPullRequestReviewsResponse, error)
	// Search & User Operations
	SearchCode(ctx context.Context, in *SearchCodeRequest, opts ...grpc.CallOption) (*SearchCodeResponse, error)
	SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
}

type gitHubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitHubServiceClient(cc grpc.ClientConnInterface) GitHubServiceClient {
	return &gitHubServiceClient{cc}
}

func (c *gitHubServiceClient) CreateRepository(ctx context.Context, in *CreateRepositoryRequest, opts ...grpc.CallOption) (*CreateRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRepositoryResponse)
	err := c.cc.Invoke(ctx, GitHubService_CreateRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) SearchRepositories(ctx context.Context, in *SearchRepositoriesRequest, opts ...grpc.CallOption) (*SearchRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchRepositoriesResponse)
	err := c.cc.Invoke(ctx, GitHubService_SearchRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*GetRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepositoryResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) ForkRepository(ctx context.Context, in *ForkRepositoryRequest, opts ...grpc.CallOption) (*ForkRepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkRepositoryResponse)
	err := c.cc.Invoke(ctx, GitHubService_ForkRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetFileContents(ctx context.Context, in *GetFileContentsRequest, opts ...grpc.CallOption) (*GetFileContentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileContentsResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetFileContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) CreateOrUpdateFile(ctx context.Context, in *CreateOrUpdateFileRequest, opts ...grpc.CallOption) (*FileCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileCommitResponse)
	err := c.cc.Invoke(ctx, GitHubService_CreateOrUpdateFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) PushFiles(ctx context.Context, in *PushFilesRequest, opts ...grpc.CallOption) (*PushFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushFilesResponse)
	err := c.cc.Invoke(ctx, GitHubService_PushFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBranchResponse)
	err := c.cc.Invoke(ctx, GitHubService_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, GitHubService_ListCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) CreateIssue(ctx context.Context, in *CreateIssueRequest, opts ...grpc.CallOption) (*CreateIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIssueResponse)
	err := c.cc.Invoke(ctx, GitHubService_CreateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) ListIssues(ctx context.Context, in *ListIssuesRequest, opts ...grpc.CallOption) (*ListIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssuesResponse)
	err := c.cc.Invoke(ctx, GitHubService_ListIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetIssue(ctx context.Context, in *GetIssueRequest, opts ...grpc.CallOption) (*GetIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIssueResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*UpdateIssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateIssueResponse)
	err := c.cc.Invoke(ctx, GitHubService_UpdateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) AddIssueComment(ctx context.Context, in *AddIssueCommentRequest, opts ...grpc.CallOption) (*AddIssueCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddIssueCommentResponse)
	err := c.cc.Invoke(ctx, GitHubService_AddIssueComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) SearchIssues(ctx context.Context, in *SearchIssuesRequest, opts ...grpc.CallOption) (*SearchIssuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchIssuesResponse)
	err := c.cc.Invoke(ctx, GitHubService_SearchIssues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) CreatePullRequest(ctx context.Context, in *CreatePullRequestRequest, opts ...grpc.CallOption) (*CreatePullRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePullRequestResponse)
	err := c.cc.Invoke(ctx, GitHubService_CreatePullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetPullRequest(ctx context.Context, in *GetPullRequestRequest, opts ...grpc.CallOption) (*GetPullRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullRequestResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetPullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) ListPullRequests(ctx context.Context, in *ListPullRequestsRequest, opts ...grpc.CallOption) (*ListPullRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPullRequestsResponse)
	err := c.cc.Invoke(ctx, GitHubService_ListPullRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) CreatePullRequestReview(ctx context.Context, in *CreatePullRequestReviewRequest, opts ...grpc.CallOption) (*CreatePullRequestReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePullRequestReviewResponse)
	err := c.cc.Invoke(ctx, GitHubService_CreatePullRequestReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) MergePullRequest(ctx context.Context, in *MergePullRequestRequest, opts ...grpc.CallOption) (*MergePullRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergePullRequestResponse)
	err := c.cc.Invoke(ctx, GitHubService_MergePullRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetPullRequestFiles(ctx context.Context, in *GetPullRequestFilesRequest, opts ...grpc.CallOption) (*GetPullRequestFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullRequestFilesResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetPullRequestFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetPullRequestStatus(ctx context.Context, in *GetPullRequestStatusRequest, opts ...grpc.CallOption) (*GetPullRequestStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullRequestStatusResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetPullRequestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) UpdatePullRequestBranch(ctx context.Context, in *UpdatePullRequestBranchRequest, opts ...grpc.CallOption) (*UpdatePullRequestBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePullRequestBranchResponse)
	err := c.cc.Invoke(ctx, GitHubService_UpdatePullRequestBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetPullRequestComments(ctx context.Context, in *GetPullRequestCommentsRequest, opts ...grpc.CallOption) (*GetPullRequestCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullRequestCommentsResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetPullRequestComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) GetPullRequestReviews(ctx context.Context, in *GetPullRequestReviewsRequest, opts ...grpc.CallOption) (*GetPullRequestReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPullRequestReviewsResponse)
	err := c.cc.Invoke(ctx, GitHubService_GetPullRequestReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) SearchCode(ctx context.Context, in *SearchCodeRequest, opts ...grpc.CallOption) (*SearchCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCodeResponse)
	err := c.cc.Invoke(ctx, GitHubService_SearchCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubServiceClient) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUsersResponse)
	err := c.cc.Invoke(ctx, GitHubService_SearchUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitHubServiceServer is the server API for GitHubService service.
// All implementations must embed UnimplementedGitHubServiceServer
// for forward compatibility.
//
// Service definition for GitHub MCP
type GitHubServiceServer interface {
	// Repository Operations
	CreateRepository(context.Context, *CreateRepositoryRequest) (*CreateRepositoryResponse, error)
	SearchRepositories(context.Context, *SearchRepositoriesRequest) (*SearchRepositoriesResponse, error)
	GetRepository(context.Context, *GetRepositoryRequest) (*GetRepositoryResponse, error)
	ForkRepository(context.Context, *ForkRepositoryRequest) (*ForkRepositoryResponse, error)
	// File Operations
	GetFileContents(context.Context, *GetFileContentsRequest) (*GetFileContentsResponse, error)
	CreateOrUpdateFile(context.Context, *CreateOrUpdateFileRequest) (*FileCommitResponse, error)
	PushFiles(context.Context, *PushFilesRequest) (*PushFilesResponse, error)
	// Branch & Commit Operations
	CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error)
	ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error)
	// Issue Operations
	CreateIssue(context.Context, *CreateIssueRequest) (*CreateIssueResponse, error)
	ListIssues(context.Context, *ListIssuesRequest) (*ListIssuesResponse, error)
	GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error)
	UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error)
	AddIssueComment(context.Context, *AddIssueCommentRequest) (*AddIssueCommentResponse, error)
	SearchIssues(context.Context, *SearchIssuesRequest) (*SearchIssuesResponse, error)
	// Pull Request Operations
	CreatePullRequest(context.Context, *CreatePullRequestRequest) (*CreatePullRequestResponse, error)
	GetPullRequest(context.Context, *GetPullRequestRequest) (*GetPullRequestResponse, error)
	ListPullRequests(context.Context, *ListPullRequestsRequest) (*ListPullRequestsResponse, error)
	CreatePullRequestReview(context.Context, *CreatePullRequestReviewRequest) (*CreatePullRequestReviewResponse, error)
	MergePullRequest(context.Context, *MergePullRequestRequest) (*MergePullRequestResponse, error)
	GetPullRequestFiles(context.Context, *GetPullRequestFilesRequest) (*GetPullRequestFilesResponse, error)
	GetPullRequestStatus(context.Context, *GetPullRequestStatusRequest) (*GetPullRequestStatusResponse, error)
	UpdatePullRequestBranch(context.Context, *UpdatePullRequestBranchRequest) (*UpdatePullRequestBranchResponse, error)
	GetPullRequestComments(context.Context, *GetPullRequestCommentsRequest) (*GetPullRequestCommentsResponse, error)
	GetPullRequestReviews(context.Context, *GetPullRequestReviewsRequest) (*GetPullRequestReviewsResponse, error)
	// Search & User Operations
	SearchCode(context.Context, *SearchCodeRequest) (*SearchCodeResponse, error)
	SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error)
	mustEmbedUnimplementedGitHubServiceServer()
}

// UnimplementedGitHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitHubServiceServer struct{}

func (UnimplementedGitHubServiceServer) CreateRepository(context.Context, *CreateRepositoryRequest) (*CreateRepositoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRepository not implemented")
}
func (UnimplementedGitHubServiceServer) SearchRepositories(context.Context, *SearchRepositoriesRequest) (*SearchRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchRepositories not implemented")
}
func (UnimplementedGitHubServiceServer) GetRepository(context.Context, *GetRepositoryRequest) (*GetRepositoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepository not implemented")
}
func (UnimplementedGitHubServiceServer) ForkRepository(context.Context, *ForkRepositoryRequest) (*ForkRepositoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForkRepository not implemented")
}
func (UnimplementedGitHubServiceServer) GetFileContents(context.Context, *GetFileContentsRequest) (*GetFileContentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileContents not implemented")
}
func (UnimplementedGitHubServiceServer) CreateOrUpdateFile(context.Context, *CreateOrUpdateFileRequest) (*FileCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateFile not implemented")
}
func (UnimplementedGitHubServiceServer) PushFiles(context.Context, *PushFilesRequest) (*PushFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushFiles not implemented")
}
func (UnimplementedGitHubServiceServer) CreateBranch(context.Context, *CreateBranchRequest) (*CreateBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedGitHubServiceServer) ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommits not implemented")
}
func (UnimplementedGitHubServiceServer) CreateIssue(context.Context, *CreateIssueRequest) (*CreateIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateIssue not implemented")
}
func (UnimplementedGitHubServiceServer) ListIssues(context.Context, *ListIssuesRequest) (*ListIssuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIssues not implemented")
}
func (UnimplementedGitHubServiceServer) GetIssue(context.Context, *GetIssueRequest) (*GetIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIssue not implemented")
}
func (UnimplementedGitHubServiceServer) UpdateIssue(context.Context, *UpdateIssueRequest) (*UpdateIssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIssue not implemented")
}
func (UnimplementedGitHubServiceServer) AddIssueComment(context.Context, *AddIssueCommentRequest) (*AddIssueCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddIssueComment not implemented")
}
func (UnimplementedGitHubServiceServer) SearchIssues(context.Context, *SearchIssuesRequest) (*SearchIssuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchIssues not implemented")
}
func (UnimplementedGitHubServiceServer) CreatePullRequest(context.Context, *CreatePullRequestRequest) (*CreatePullRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePullRequest not implemented")
}
func (UnimplementedGitHubServiceServer) GetPullRequest(context.Context, *GetPullRequestRequest) (*GetPullRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullRequest not implemented")
}
func (UnimplementedGitHubServiceServer) ListPullRequests(context.Context, *ListPullRequestsRequest) (*ListPullRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPullRequests not implemented")
}
func (UnimplementedGitHubServiceServer) CreatePullRequestReview(context.Context, *CreatePullRequestReviewRequest) (*CreatePullRequestReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePullRequestReview not implemented")
}
func (UnimplementedGitHubServiceServer) MergePullRequest(context.Context, *MergePullRequestRequest) (*MergePullRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MergePullRequest not implemented")
}
func (UnimplementedGitHubServiceServer) GetPullRequestFiles(context.Context, *GetPullRequestFilesRequest) (*GetPullRequestFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullRequestFiles not implemented")
}
func (UnimplementedGitHubServiceServer) GetPullRequestStatus(context.Context, *GetPullRequestStatusRequest) (*GetPullRequestStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullRequestStatus not implemented")
}
func (UnimplementedGitHubServiceServer) UpdatePullRequestBranch(context.Context, *UpdatePullRequestBranchRequest) (*UpdatePullRequestBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePullRequestBranch not implemented")
}
func (UnimplementedGitHubServiceServer) GetPullRequestComments(context.Context, *GetPullRequestCommentsRequest) (*GetPullRequestCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullRequestComments not implemented")
}
func (UnimplementedGitHubServiceServer) GetPullRequestReviews(context.Context, *GetPullRequestReviewsRequest) (*GetPullRequestReviewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPullRequestReviews not implemented")
}
func (UnimplementedGitHubServiceServer) SearchCode(context.Context, *SearchCodeRequest) (*SearchCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCode not implemented")
}
func (UnimplementedGitHubServiceServer) SearchUsers(context.Context, *SearchUsersRequest) (*SearchUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUsers not implemented")
}
func (UnimplementedGitHubServiceServer) mustEmbedUnimplementedGitHubServiceServer() {}
func (UnimplementedGitHubServiceServer) testEmbeddedByValue()                       {}

// UnsafeGitHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitHubServiceServer will
// result in compilation errors.
type UnsafeGitHubServiceServer interface {
	mustEmbedUnimplementedGitHubServiceServer()
}

func RegisterGitHubServiceServer(s grpc.ServiceRegistrar, srv GitHubServiceServer) {
	// If the following call panics, it indicates UnimplementedGitHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitHubService_ServiceDesc, srv)
}

func _GitHubService_CreateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).CreateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_CreateRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).CreateRepository(ctx, req.(*CreateRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_SearchRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).SearchRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_SearchRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).SearchRepositories(ctx, req.(*SearchRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetRepository(ctx, req.(*GetRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_ForkRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).ForkRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_ForkRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).ForkRepository(ctx, req.(*ForkRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetFileContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetFileContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetFileContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetFileContents(ctx, req.(*GetFileContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_CreateOrUpdateFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).CreateOrUpdateFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_CreateOrUpdateFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).CreateOrUpdateFile(ctx, req.(*CreateOrUpdateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_PushFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).PushFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_PushFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).PushFiles(ctx, req.(*PushFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_ListCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).ListCommits(ctx, req.(*ListCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_CreateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).CreateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_CreateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).CreateIssue(ctx, req.(*CreateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_ListIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).ListIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_ListIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).ListIssues(ctx, req.(*ListIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetIssue(ctx, req.(*GetIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_UpdateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).UpdateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_UpdateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).UpdateIssue(ctx, req.(*UpdateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_AddIssueComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddIssueCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).AddIssueComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_AddIssueComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).AddIssueComment(ctx, req.(*AddIssueCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_SearchIssues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchIssuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).SearchIssues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_SearchIssues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).SearchIssues(ctx, req.(*SearchIssuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_CreatePullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).CreatePullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_CreatePullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).CreatePullRequest(ctx, req.(*CreatePullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetPullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetPullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetPullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetPullRequest(ctx, req.(*GetPullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_ListPullRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPullRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).ListPullRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_ListPullRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).ListPullRequests(ctx, req.(*ListPullRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_CreatePullRequestReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePullRequestReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).CreatePullRequestReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_CreatePullRequestReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).CreatePullRequestReview(ctx, req.(*CreatePullRequestReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_MergePullRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergePullRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).MergePullRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_MergePullRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).MergePullRequest(ctx, req.(*MergePullRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetPullRequestFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullRequestFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetPullRequestFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetPullRequestFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetPullRequestFiles(ctx, req.(*GetPullRequestFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetPullRequestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullRequestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetPullRequestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetPullRequestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetPullRequestStatus(ctx, req.(*GetPullRequestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_UpdatePullRequestBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePullRequestBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).UpdatePullRequestBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_UpdatePullRequestBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).UpdatePullRequestBranch(ctx, req.(*UpdatePullRequestBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetPullRequestComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullRequestCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetPullRequestComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetPullRequestComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetPullRequestComments(ctx, req.(*GetPullRequestCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_GetPullRequestReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPullRequestReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).GetPullRequestReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_GetPullRequestReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).GetPullRequestReviews(ctx, req.(*GetPullRequestReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_SearchCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).SearchCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_SearchCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).SearchCode(ctx, req.(*SearchCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubService_SearchUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubServiceServer).SearchUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubService_SearchUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubServiceServer).SearchUsers(ctx, req.(*SearchUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GitHubService_ServiceDesc is the grpc.ServiceDesc for GitHubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitHubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tucker.mcproto.github.v1.GitHubService",
	HandlerType: (*GitHubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRepository",
			Handler:    _GitHubService_CreateRepository_Handler,
		},
		{
			MethodName: "SearchRepositories",
			Handler:    _GitHubService_SearchRepositories_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _GitHubService_GetRepository_Handler,
		},
		{
			MethodName: "ForkRepository",
			Handler:    _GitHubService_ForkRepository_Handler,
		},
		{
			MethodName: "GetFileContents",
			Handler:    _GitHubService_GetFileContents_Handler,
		},
		{
			MethodName: "CreateOrUpdateFile",
			Handler:    _GitHubService_CreateOrUpdateFile_Handler,
		},
		{
			MethodName: "PushFiles",
			Handler:    _GitHubService_PushFiles_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _GitHubService_CreateBranch_Handler,
		},
		{
			MethodName: "ListCommits",
			Handler:    _GitHubService_ListCommits_Handler,
		},
		{
			MethodName: "CreateIssue",
			Handler:    _GitHubService_CreateIssue_Handler,
		},
		{
			MethodName: "ListIssues",
			Handler:    _GitHubService_ListIssues_Handler,
		},
		{
			MethodName: "GetIssue",
			Handler:    _GitHubService_GetIssue_Handler,
		},
		{
			MethodName: "UpdateIssue",
			Handler:    _GitHubService_UpdateIssue_Handler,
		},
		{
			MethodName: "AddIssueComment",
			Handler:    _GitHubService_AddIssueComment_Handler,
		},
		{
			MethodName: "SearchIssues",
			Handler:    _GitHubService_SearchIssues_Handler,
		},
		{
			MethodName: "CreatePullRequest",
			Handler:    _GitHubService_CreatePullRequest_Handler,
		},
		{
			MethodName: "GetPullRequest",
			Handler:    _GitHubService_GetPullRequest_Handler,
		},
		{
			MethodName: "ListPullRequests",
			Handler:    _GitHubService_ListPullRequests_Handler,
		},
		{
			MethodName: "CreatePullRequestReview",
			Handler:    _GitHubService_CreatePullRequestReview_Handler,
		},
		{
			MethodName: "MergePullRequest",
			Handler:    _GitHubService_MergePullRequest_Handler,
		},
		{
			MethodName: "GetPullRequestFiles",
			Handler:    _GitHubService_GetPullRequestFiles_Handler,
		},
		{
			MethodName: "GetPullRequestStatus",
			Handler:    _GitHubService_GetPullRequestStatus_Handler,
		},
		{
			MethodName: "UpdatePullRequestBranch",
			Handler:    _GitHubService_UpdatePullRequestBranch_Handler,
		},
		{
			MethodName: "GetPullRequestComments",
			Handler:    _GitHubService_GetPullRequestComments_Handler,
		},
		{
			MethodName: "GetPullRequestReviews",
			Handler:    _GitHubService_GetPullRequestReviews_Handler,
		},
		{
			MethodName: "SearchCode",
			Handler:    _GitHubService_SearchCode_Handler,
		},
		{
			MethodName: "SearchUsers",
			Handler:    _GitHubService_SearchUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.proto",
}
