"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Event(_message.Message):
    """A generic data event in the pipeline"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    DOMAIN_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    domain: _builtins.str
    """e.g., "marketing", "auth", "billing" """
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def payload(self) -> _struct_pb2.Struct:
        """The actual variable payload"""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        domain: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        payload: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload", "timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["domain", b"domain", "id", b"id", "payload", b"payload", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class ExtractRequest(_message.Message):
    """Extraction Request"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FiltersEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SOURCE_ID_FIELD_NUMBER: _builtins.int
    BATCH_SIZE_FIELD_NUMBER: _builtins.int
    FILTERS_FIELD_NUMBER: _builtins.int
    source_id: _builtins.str
    batch_size: _builtins.int
    @_builtins.property
    def filters(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        source_id: _builtins.str = ...,
        batch_size: _builtins.int = ...,
        filters: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["batch_size", b"batch_size", "filters", b"filters", "source_id", b"source_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ExtractRequest: _TypeAlias = ExtractRequest  # noqa: Y015

@_typing.final
class TransformRequest(_message.Message):
    """Transformation/Mapping Rule"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Rule(_message.Message):
        """A complex rule set showing nested schema overhead"""

        DESCRIPTOR: _descriptor.Descriptor

        TARGET_FIELD_FIELD_NUMBER: _builtins.int
        TRANSFORM_OP_FIELD_NUMBER: _builtins.int
        FALLBACK_VALUE_FIELD_NUMBER: _builtins.int
        target_field: _builtins.str
        transform_op: _builtins.str
        """e.g., "uppercase", "hash", "mask" """
        fallback_value: _builtins.str
        def __init__(
            self,
            *,
            target_field: _builtins.str = ...,
            transform_op: _builtins.str = ...,
            fallback_value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["fallback_value", b"fallback_value", "target_field", b"target_field", "transform_op", b"transform_op"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    EVENT_FIELD_NUMBER: _builtins.int
    RULES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def event(self) -> Global___Event: ...
    @_builtins.property
    def rules(self) -> _containers.RepeatedCompositeFieldContainer[Global___TransformRequest.Rule]: ...
    def __init__(
        self,
        *,
        event: Global___Event | None = ...,
        rules: _abc.Iterable[Global___TransformRequest.Rule] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event", "rules", b"rules"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TransformRequest: _TypeAlias = TransformRequest  # noqa: Y015

@_typing.final
class LoadRequest(_message.Message):
    """Loading/Sink Request"""

    DESCRIPTOR: _descriptor.Descriptor

    TARGET_BUCKET_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    OVERWRITE_FIELD_NUMBER: _builtins.int
    target_bucket: _builtins.str
    overwrite: _builtins.bool
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]: ...
    def __init__(
        self,
        *,
        target_bucket: _builtins.str = ...,
        events: _abc.Iterable[Global___Event] | None = ...,
        overwrite: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["events", b"events", "overwrite", b"overwrite", "target_bucket", b"target_bucket"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoadRequest: _TypeAlias = LoadRequest  # noqa: Y015

@_typing.final
class LoadResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROCESSED_COUNT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    processed_count: _builtins.int
    status: _builtins.str
    def __init__(
        self,
        *,
        processed_count: _builtins.int = ...,
        status: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["processed_count", b"processed_count", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoadResponse: _TypeAlias = LoadResponse  # noqa: Y015
