"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import analytics_pb2 as _analytics_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AnalyticsServiceStub:
    """A tool definition inside the BSR"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AnalyticsServiceAsyncStub: ...
    Extract: _grpc.UnaryStreamMultiCallable[_analytics_pb2.ExtractRequest, _analytics_pb2.Event]
    Transform: _grpc.UnaryUnaryMultiCallable[_analytics_pb2.TransformRequest, _analytics_pb2.Event]
    Load: _grpc.UnaryUnaryMultiCallable[_analytics_pb2.LoadRequest, _analytics_pb2.LoadResponse]

@_typing.type_check_only
class AnalyticsServiceAsyncStub(AnalyticsServiceStub):
    """A tool definition inside the BSR"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Extract: _aio.UnaryStreamMultiCallable[_analytics_pb2.ExtractRequest, _analytics_pb2.Event]  # type: ignore[assignment]
    Transform: _aio.UnaryUnaryMultiCallable[_analytics_pb2.TransformRequest, _analytics_pb2.Event]  # type: ignore[assignment]
    Load: _aio.UnaryUnaryMultiCallable[_analytics_pb2.LoadRequest, _analytics_pb2.LoadResponse]  # type: ignore[assignment]

class AnalyticsServiceServicer(metaclass=_abc_1.ABCMeta):
    """A tool definition inside the BSR"""

    @_abc_1.abstractmethod
    def Extract(
        self,
        request: _analytics_pb2.ExtractRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_analytics_pb2.Event], _abc.AsyncIterator[_analytics_pb2.Event]]: ...

    @_abc_1.abstractmethod
    def Transform(
        self,
        request: _analytics_pb2.TransformRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analytics_pb2.Event, _abc.Awaitable[_analytics_pb2.Event]]: ...

    @_abc_1.abstractmethod
    def Load(
        self,
        request: _analytics_pb2.LoadRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_analytics_pb2.LoadResponse, _abc.Awaitable[_analytics_pb2.LoadResponse]]: ...

def add_AnalyticsServiceServicer_to_server(servicer: AnalyticsServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
