# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import discovery_pb2 as discovery__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in discovery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscoveryServiceStub(object):
    """The Discovery Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchRegistry = channel.unary_unary(
                '/misfit.discovery.v1.DiscoveryService/SearchRegistry',
                request_serializer=discovery__pb2.SearchRegistryRequest.SerializeToString,
                response_deserializer=discovery__pb2.SearchRegistryResponse.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """The Discovery Service definition
    """

    def SearchRegistry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchRegistry': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRegistry,
                    request_deserializer=discovery__pb2.SearchRegistryRequest.FromString,
                    response_serializer=discovery__pb2.SearchRegistryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'misfit.discovery.v1.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('misfit.discovery.v1.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """The Discovery Service definition
    """

    @staticmethod
    def SearchRegistry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/misfit.discovery.v1.DiscoveryService/SearchRegistry',
            discovery__pb2.SearchRegistryRequest.SerializeToString,
            discovery__pb2.SearchRegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
