# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: discovery.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64iscovery.proto\x12\x13misfit.discovery.v1\"5\n\x15SearchRegistryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"C\n\rToolCandidate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x62sr_ref\x18\x03 \x01(\t\"P\n\x16SearchRegistryResponse\x12\x36\n\ncandidates\x18\x01 \x03(\x0b\x32\".misfit.discovery.v1.ToolCandidate2}\n\x10\x44iscoveryService\x12i\n\x0eSearchRegistry\x12*.misfit.discovery.v1.SearchRegistryRequest\x1a+.misfit.discovery.v1.SearchRegistryResponseB1Z/github.com/misfitdev/proto-mcp/go/pkg/discoveryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/misfitdev/proto-mcp/go/pkg/discovery'
  _globals['_SEARCHREGISTRYREQUEST']._serialized_start=40
  _globals['_SEARCHREGISTRYREQUEST']._serialized_end=93
  _globals['_TOOLCANDIDATE']._serialized_start=95
  _globals['_TOOLCANDIDATE']._serialized_end=162
  _globals['_SEARCHREGISTRYRESPONSE']._serialized_start=164
  _globals['_SEARCHREGISTRYRESPONSE']._serialized_end=244
  _globals['_DISCOVERYSERVICE']._serialized_start=246
  _globals['_DISCOVERYSERVICE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
