"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SearchRegistryRequest(_message.Message):
    """Request to search for tools/messages in the registry"""

    DESCRIPTOR: _descriptor.Descriptor

    QUERY_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    query: _builtins.str
    limit: _builtins.int
    def __init__(
        self,
        *,
        query: _builtins.str = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["limit", b"limit", "query", b"query"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchRegistryRequest: _TypeAlias = SearchRegistryRequest  # noqa: Y015

@_typing.final
class ToolCandidate(_message.Message):
    """A single discovery result"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    BSR_REF_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    description: _builtins.str
    bsr_ref: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        bsr_ref: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bsr_ref", b"bsr_ref", "description", b"description", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ToolCandidate: _TypeAlias = ToolCandidate  # noqa: Y015

@_typing.final
class SearchRegistryResponse(_message.Message):
    """Response containing potential tool matches"""

    DESCRIPTOR: _descriptor.Descriptor

    CANDIDATES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def candidates(self) -> _containers.RepeatedCompositeFieldContainer[Global___ToolCandidate]: ...
    def __init__(
        self,
        *,
        candidates: _abc.Iterable[Global___ToolCandidate] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["candidates", b"candidates"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchRegistryResponse: _TypeAlias = SearchRegistryResponse  # noqa: Y015
