"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import github_pb2 as _github_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class GitHubServiceStub:
    """Service definition for GitHub MCP"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> GitHubServiceAsyncStub: ...
    CreateRepository: _grpc.UnaryUnaryMultiCallable[_github_pb2.CreateRepositoryRequest, _github_pb2.CreateRepositoryResponse]
    """Repository Operations"""
    SearchRepositories: _grpc.UnaryUnaryMultiCallable[_github_pb2.SearchRepositoriesRequest, _github_pb2.SearchRepositoriesResponse]
    GetRepository: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetRepositoryRequest, _github_pb2.GetRepositoryResponse]
    ForkRepository: _grpc.UnaryUnaryMultiCallable[_github_pb2.ForkRepositoryRequest, _github_pb2.ForkRepositoryResponse]
    GetFileContents: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetFileContentsRequest, _github_pb2.GetFileContentsResponse]
    """File Operations"""
    CreateOrUpdateFile: _grpc.UnaryUnaryMultiCallable[_github_pb2.CreateOrUpdateFileRequest, _github_pb2.FileCommitResponse]
    PushFiles: _grpc.UnaryUnaryMultiCallable[_github_pb2.PushFilesRequest, _github_pb2.PushFilesResponse]
    CreateBranch: _grpc.UnaryUnaryMultiCallable[_github_pb2.CreateBranchRequest, _github_pb2.CreateBranchResponse]
    """Branch & Commit Operations"""
    ListCommits: _grpc.UnaryUnaryMultiCallable[_github_pb2.ListCommitsRequest, _github_pb2.ListCommitsResponse]
    CreateIssue: _grpc.UnaryUnaryMultiCallable[_github_pb2.CreateIssueRequest, _github_pb2.CreateIssueResponse]
    """Issue Operations"""
    ListIssues: _grpc.UnaryUnaryMultiCallable[_github_pb2.ListIssuesRequest, _github_pb2.ListIssuesResponse]
    GetIssue: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetIssueRequest, _github_pb2.GetIssueResponse]
    UpdateIssue: _grpc.UnaryUnaryMultiCallable[_github_pb2.UpdateIssueRequest, _github_pb2.UpdateIssueResponse]
    AddIssueComment: _grpc.UnaryUnaryMultiCallable[_github_pb2.AddIssueCommentRequest, _github_pb2.AddIssueCommentResponse]
    SearchIssues: _grpc.UnaryUnaryMultiCallable[_github_pb2.SearchIssuesRequest, _github_pb2.SearchIssuesResponse]
    CreatePullRequest: _grpc.UnaryUnaryMultiCallable[_github_pb2.CreatePullRequestRequest, _github_pb2.CreatePullRequestResponse]
    """Pull Request Operations"""
    GetPullRequest: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestRequest, _github_pb2.GetPullRequestResponse]
    ListPullRequests: _grpc.UnaryUnaryMultiCallable[_github_pb2.ListPullRequestsRequest, _github_pb2.ListPullRequestsResponse]
    CreatePullRequestReview: _grpc.UnaryUnaryMultiCallable[_github_pb2.CreatePullRequestReviewRequest, _github_pb2.CreatePullRequestReviewResponse]
    MergePullRequest: _grpc.UnaryUnaryMultiCallable[_github_pb2.MergePullRequestRequest, _github_pb2.MergePullRequestResponse]
    GetPullRequestFiles: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestFilesRequest, _github_pb2.GetPullRequestFilesResponse]
    GetPullRequestStatus: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestStatusRequest, _github_pb2.GetPullRequestStatusResponse]
    UpdatePullRequestBranch: _grpc.UnaryUnaryMultiCallable[_github_pb2.UpdatePullRequestBranchRequest, _github_pb2.UpdatePullRequestBranchResponse]
    GetPullRequestComments: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestCommentsRequest, _github_pb2.GetPullRequestCommentsResponse]
    GetPullRequestReviews: _grpc.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestReviewsRequest, _github_pb2.GetPullRequestReviewsResponse]
    SearchCode: _grpc.UnaryUnaryMultiCallable[_github_pb2.SearchCodeRequest, _github_pb2.SearchCodeResponse]
    """Search & User Operations"""
    SearchUsers: _grpc.UnaryUnaryMultiCallable[_github_pb2.SearchUsersRequest, _github_pb2.SearchUsersResponse]

@_typing.type_check_only
class GitHubServiceAsyncStub(GitHubServiceStub):
    """Service definition for GitHub MCP"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    CreateRepository: _aio.UnaryUnaryMultiCallable[_github_pb2.CreateRepositoryRequest, _github_pb2.CreateRepositoryResponse]  # type: ignore[assignment]
    """Repository Operations"""
    SearchRepositories: _aio.UnaryUnaryMultiCallable[_github_pb2.SearchRepositoriesRequest, _github_pb2.SearchRepositoriesResponse]  # type: ignore[assignment]
    GetRepository: _aio.UnaryUnaryMultiCallable[_github_pb2.GetRepositoryRequest, _github_pb2.GetRepositoryResponse]  # type: ignore[assignment]
    ForkRepository: _aio.UnaryUnaryMultiCallable[_github_pb2.ForkRepositoryRequest, _github_pb2.ForkRepositoryResponse]  # type: ignore[assignment]
    GetFileContents: _aio.UnaryUnaryMultiCallable[_github_pb2.GetFileContentsRequest, _github_pb2.GetFileContentsResponse]  # type: ignore[assignment]
    """File Operations"""
    CreateOrUpdateFile: _aio.UnaryUnaryMultiCallable[_github_pb2.CreateOrUpdateFileRequest, _github_pb2.FileCommitResponse]  # type: ignore[assignment]
    PushFiles: _aio.UnaryUnaryMultiCallable[_github_pb2.PushFilesRequest, _github_pb2.PushFilesResponse]  # type: ignore[assignment]
    CreateBranch: _aio.UnaryUnaryMultiCallable[_github_pb2.CreateBranchRequest, _github_pb2.CreateBranchResponse]  # type: ignore[assignment]
    """Branch & Commit Operations"""
    ListCommits: _aio.UnaryUnaryMultiCallable[_github_pb2.ListCommitsRequest, _github_pb2.ListCommitsResponse]  # type: ignore[assignment]
    CreateIssue: _aio.UnaryUnaryMultiCallable[_github_pb2.CreateIssueRequest, _github_pb2.CreateIssueResponse]  # type: ignore[assignment]
    """Issue Operations"""
    ListIssues: _aio.UnaryUnaryMultiCallable[_github_pb2.ListIssuesRequest, _github_pb2.ListIssuesResponse]  # type: ignore[assignment]
    GetIssue: _aio.UnaryUnaryMultiCallable[_github_pb2.GetIssueRequest, _github_pb2.GetIssueResponse]  # type: ignore[assignment]
    UpdateIssue: _aio.UnaryUnaryMultiCallable[_github_pb2.UpdateIssueRequest, _github_pb2.UpdateIssueResponse]  # type: ignore[assignment]
    AddIssueComment: _aio.UnaryUnaryMultiCallable[_github_pb2.AddIssueCommentRequest, _github_pb2.AddIssueCommentResponse]  # type: ignore[assignment]
    SearchIssues: _aio.UnaryUnaryMultiCallable[_github_pb2.SearchIssuesRequest, _github_pb2.SearchIssuesResponse]  # type: ignore[assignment]
    CreatePullRequest: _aio.UnaryUnaryMultiCallable[_github_pb2.CreatePullRequestRequest, _github_pb2.CreatePullRequestResponse]  # type: ignore[assignment]
    """Pull Request Operations"""
    GetPullRequest: _aio.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestRequest, _github_pb2.GetPullRequestResponse]  # type: ignore[assignment]
    ListPullRequests: _aio.UnaryUnaryMultiCallable[_github_pb2.ListPullRequestsRequest, _github_pb2.ListPullRequestsResponse]  # type: ignore[assignment]
    CreatePullRequestReview: _aio.UnaryUnaryMultiCallable[_github_pb2.CreatePullRequestReviewRequest, _github_pb2.CreatePullRequestReviewResponse]  # type: ignore[assignment]
    MergePullRequest: _aio.UnaryUnaryMultiCallable[_github_pb2.MergePullRequestRequest, _github_pb2.MergePullRequestResponse]  # type: ignore[assignment]
    GetPullRequestFiles: _aio.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestFilesRequest, _github_pb2.GetPullRequestFilesResponse]  # type: ignore[assignment]
    GetPullRequestStatus: _aio.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestStatusRequest, _github_pb2.GetPullRequestStatusResponse]  # type: ignore[assignment]
    UpdatePullRequestBranch: _aio.UnaryUnaryMultiCallable[_github_pb2.UpdatePullRequestBranchRequest, _github_pb2.UpdatePullRequestBranchResponse]  # type: ignore[assignment]
    GetPullRequestComments: _aio.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestCommentsRequest, _github_pb2.GetPullRequestCommentsResponse]  # type: ignore[assignment]
    GetPullRequestReviews: _aio.UnaryUnaryMultiCallable[_github_pb2.GetPullRequestReviewsRequest, _github_pb2.GetPullRequestReviewsResponse]  # type: ignore[assignment]
    SearchCode: _aio.UnaryUnaryMultiCallable[_github_pb2.SearchCodeRequest, _github_pb2.SearchCodeResponse]  # type: ignore[assignment]
    """Search & User Operations"""
    SearchUsers: _aio.UnaryUnaryMultiCallable[_github_pb2.SearchUsersRequest, _github_pb2.SearchUsersResponse]  # type: ignore[assignment]

class GitHubServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service definition for GitHub MCP"""

    @_abc_1.abstractmethod
    def CreateRepository(
        self,
        request: _github_pb2.CreateRepositoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.CreateRepositoryResponse, _abc.Awaitable[_github_pb2.CreateRepositoryResponse]]:
        """Repository Operations"""

    @_abc_1.abstractmethod
    def SearchRepositories(
        self,
        request: _github_pb2.SearchRepositoriesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.SearchRepositoriesResponse, _abc.Awaitable[_github_pb2.SearchRepositoriesResponse]]: ...

    @_abc_1.abstractmethod
    def GetRepository(
        self,
        request: _github_pb2.GetRepositoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetRepositoryResponse, _abc.Awaitable[_github_pb2.GetRepositoryResponse]]: ...

    @_abc_1.abstractmethod
    def ForkRepository(
        self,
        request: _github_pb2.ForkRepositoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.ForkRepositoryResponse, _abc.Awaitable[_github_pb2.ForkRepositoryResponse]]: ...

    @_abc_1.abstractmethod
    def GetFileContents(
        self,
        request: _github_pb2.GetFileContentsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetFileContentsResponse, _abc.Awaitable[_github_pb2.GetFileContentsResponse]]:
        """File Operations"""

    @_abc_1.abstractmethod
    def CreateOrUpdateFile(
        self,
        request: _github_pb2.CreateOrUpdateFileRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.FileCommitResponse, _abc.Awaitable[_github_pb2.FileCommitResponse]]: ...

    @_abc_1.abstractmethod
    def PushFiles(
        self,
        request: _github_pb2.PushFilesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.PushFilesResponse, _abc.Awaitable[_github_pb2.PushFilesResponse]]: ...

    @_abc_1.abstractmethod
    def CreateBranch(
        self,
        request: _github_pb2.CreateBranchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.CreateBranchResponse, _abc.Awaitable[_github_pb2.CreateBranchResponse]]:
        """Branch & Commit Operations"""

    @_abc_1.abstractmethod
    def ListCommits(
        self,
        request: _github_pb2.ListCommitsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.ListCommitsResponse, _abc.Awaitable[_github_pb2.ListCommitsResponse]]: ...

    @_abc_1.abstractmethod
    def CreateIssue(
        self,
        request: _github_pb2.CreateIssueRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.CreateIssueResponse, _abc.Awaitable[_github_pb2.CreateIssueResponse]]:
        """Issue Operations"""

    @_abc_1.abstractmethod
    def ListIssues(
        self,
        request: _github_pb2.ListIssuesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.ListIssuesResponse, _abc.Awaitable[_github_pb2.ListIssuesResponse]]: ...

    @_abc_1.abstractmethod
    def GetIssue(
        self,
        request: _github_pb2.GetIssueRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetIssueResponse, _abc.Awaitable[_github_pb2.GetIssueResponse]]: ...

    @_abc_1.abstractmethod
    def UpdateIssue(
        self,
        request: _github_pb2.UpdateIssueRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.UpdateIssueResponse, _abc.Awaitable[_github_pb2.UpdateIssueResponse]]: ...

    @_abc_1.abstractmethod
    def AddIssueComment(
        self,
        request: _github_pb2.AddIssueCommentRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.AddIssueCommentResponse, _abc.Awaitable[_github_pb2.AddIssueCommentResponse]]: ...

    @_abc_1.abstractmethod
    def SearchIssues(
        self,
        request: _github_pb2.SearchIssuesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.SearchIssuesResponse, _abc.Awaitable[_github_pb2.SearchIssuesResponse]]: ...

    @_abc_1.abstractmethod
    def CreatePullRequest(
        self,
        request: _github_pb2.CreatePullRequestRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.CreatePullRequestResponse, _abc.Awaitable[_github_pb2.CreatePullRequestResponse]]:
        """Pull Request Operations"""

    @_abc_1.abstractmethod
    def GetPullRequest(
        self,
        request: _github_pb2.GetPullRequestRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetPullRequestResponse, _abc.Awaitable[_github_pb2.GetPullRequestResponse]]: ...

    @_abc_1.abstractmethod
    def ListPullRequests(
        self,
        request: _github_pb2.ListPullRequestsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.ListPullRequestsResponse, _abc.Awaitable[_github_pb2.ListPullRequestsResponse]]: ...

    @_abc_1.abstractmethod
    def CreatePullRequestReview(
        self,
        request: _github_pb2.CreatePullRequestReviewRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.CreatePullRequestReviewResponse, _abc.Awaitable[_github_pb2.CreatePullRequestReviewResponse]]: ...

    @_abc_1.abstractmethod
    def MergePullRequest(
        self,
        request: _github_pb2.MergePullRequestRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.MergePullRequestResponse, _abc.Awaitable[_github_pb2.MergePullRequestResponse]]: ...

    @_abc_1.abstractmethod
    def GetPullRequestFiles(
        self,
        request: _github_pb2.GetPullRequestFilesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetPullRequestFilesResponse, _abc.Awaitable[_github_pb2.GetPullRequestFilesResponse]]: ...

    @_abc_1.abstractmethod
    def GetPullRequestStatus(
        self,
        request: _github_pb2.GetPullRequestStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetPullRequestStatusResponse, _abc.Awaitable[_github_pb2.GetPullRequestStatusResponse]]: ...

    @_abc_1.abstractmethod
    def UpdatePullRequestBranch(
        self,
        request: _github_pb2.UpdatePullRequestBranchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.UpdatePullRequestBranchResponse, _abc.Awaitable[_github_pb2.UpdatePullRequestBranchResponse]]: ...

    @_abc_1.abstractmethod
    def GetPullRequestComments(
        self,
        request: _github_pb2.GetPullRequestCommentsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetPullRequestCommentsResponse, _abc.Awaitable[_github_pb2.GetPullRequestCommentsResponse]]: ...

    @_abc_1.abstractmethod
    def GetPullRequestReviews(
        self,
        request: _github_pb2.GetPullRequestReviewsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.GetPullRequestReviewsResponse, _abc.Awaitable[_github_pb2.GetPullRequestReviewsResponse]]: ...

    @_abc_1.abstractmethod
    def SearchCode(
        self,
        request: _github_pb2.SearchCodeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.SearchCodeResponse, _abc.Awaitable[_github_pb2.SearchCodeResponse]]:
        """Search & User Operations"""

    @_abc_1.abstractmethod
    def SearchUsers(
        self,
        request: _github_pb2.SearchUsersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_github_pb2.SearchUsersResponse, _abc.Awaitable[_github_pb2.SearchUsersResponse]]: ...

def add_GitHubServiceServicer_to_server(servicer: GitHubServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
