# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import github_pb2 as github__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in github_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GitHubServiceStub(object):
    """Service definition for GitHub MCP
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRepository = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/CreateRepository',
                request_serializer=github__pb2.CreateRepositoryRequest.SerializeToString,
                response_deserializer=github__pb2.CreateRepositoryResponse.FromString,
                _registered_method=True)
        self.SearchRepositories = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/SearchRepositories',
                request_serializer=github__pb2.SearchRepositoriesRequest.SerializeToString,
                response_deserializer=github__pb2.SearchRepositoriesResponse.FromString,
                _registered_method=True)
        self.GetRepository = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetRepository',
                request_serializer=github__pb2.GetRepositoryRequest.SerializeToString,
                response_deserializer=github__pb2.GetRepositoryResponse.FromString,
                _registered_method=True)
        self.ForkRepository = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/ForkRepository',
                request_serializer=github__pb2.ForkRepositoryRequest.SerializeToString,
                response_deserializer=github__pb2.ForkRepositoryResponse.FromString,
                _registered_method=True)
        self.GetFileContents = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetFileContents',
                request_serializer=github__pb2.GetFileContentsRequest.SerializeToString,
                response_deserializer=github__pb2.GetFileContentsResponse.FromString,
                _registered_method=True)
        self.CreateOrUpdateFile = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/CreateOrUpdateFile',
                request_serializer=github__pb2.CreateOrUpdateFileRequest.SerializeToString,
                response_deserializer=github__pb2.FileCommitResponse.FromString,
                _registered_method=True)
        self.PushFiles = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/PushFiles',
                request_serializer=github__pb2.PushFilesRequest.SerializeToString,
                response_deserializer=github__pb2.PushFilesResponse.FromString,
                _registered_method=True)
        self.CreateBranch = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/CreateBranch',
                request_serializer=github__pb2.CreateBranchRequest.SerializeToString,
                response_deserializer=github__pb2.CreateBranchResponse.FromString,
                _registered_method=True)
        self.ListCommits = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/ListCommits',
                request_serializer=github__pb2.ListCommitsRequest.SerializeToString,
                response_deserializer=github__pb2.ListCommitsResponse.FromString,
                _registered_method=True)
        self.CreateIssue = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/CreateIssue',
                request_serializer=github__pb2.CreateIssueRequest.SerializeToString,
                response_deserializer=github__pb2.CreateIssueResponse.FromString,
                _registered_method=True)
        self.ListIssues = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/ListIssues',
                request_serializer=github__pb2.ListIssuesRequest.SerializeToString,
                response_deserializer=github__pb2.ListIssuesResponse.FromString,
                _registered_method=True)
        self.GetIssue = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetIssue',
                request_serializer=github__pb2.GetIssueRequest.SerializeToString,
                response_deserializer=github__pb2.GetIssueResponse.FromString,
                _registered_method=True)
        self.UpdateIssue = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/UpdateIssue',
                request_serializer=github__pb2.UpdateIssueRequest.SerializeToString,
                response_deserializer=github__pb2.UpdateIssueResponse.FromString,
                _registered_method=True)
        self.AddIssueComment = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/AddIssueComment',
                request_serializer=github__pb2.AddIssueCommentRequest.SerializeToString,
                response_deserializer=github__pb2.AddIssueCommentResponse.FromString,
                _registered_method=True)
        self.SearchIssues = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/SearchIssues',
                request_serializer=github__pb2.SearchIssuesRequest.SerializeToString,
                response_deserializer=github__pb2.SearchIssuesResponse.FromString,
                _registered_method=True)
        self.CreatePullRequest = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/CreatePullRequest',
                request_serializer=github__pb2.CreatePullRequestRequest.SerializeToString,
                response_deserializer=github__pb2.CreatePullRequestResponse.FromString,
                _registered_method=True)
        self.GetPullRequest = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetPullRequest',
                request_serializer=github__pb2.GetPullRequestRequest.SerializeToString,
                response_deserializer=github__pb2.GetPullRequestResponse.FromString,
                _registered_method=True)
        self.ListPullRequests = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/ListPullRequests',
                request_serializer=github__pb2.ListPullRequestsRequest.SerializeToString,
                response_deserializer=github__pb2.ListPullRequestsResponse.FromString,
                _registered_method=True)
        self.CreatePullRequestReview = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/CreatePullRequestReview',
                request_serializer=github__pb2.CreatePullRequestReviewRequest.SerializeToString,
                response_deserializer=github__pb2.CreatePullRequestReviewResponse.FromString,
                _registered_method=True)
        self.MergePullRequest = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/MergePullRequest',
                request_serializer=github__pb2.MergePullRequestRequest.SerializeToString,
                response_deserializer=github__pb2.MergePullRequestResponse.FromString,
                _registered_method=True)
        self.GetPullRequestFiles = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetPullRequestFiles',
                request_serializer=github__pb2.GetPullRequestFilesRequest.SerializeToString,
                response_deserializer=github__pb2.GetPullRequestFilesResponse.FromString,
                _registered_method=True)
        self.GetPullRequestStatus = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetPullRequestStatus',
                request_serializer=github__pb2.GetPullRequestStatusRequest.SerializeToString,
                response_deserializer=github__pb2.GetPullRequestStatusResponse.FromString,
                _registered_method=True)
        self.UpdatePullRequestBranch = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/UpdatePullRequestBranch',
                request_serializer=github__pb2.UpdatePullRequestBranchRequest.SerializeToString,
                response_deserializer=github__pb2.UpdatePullRequestBranchResponse.FromString,
                _registered_method=True)
        self.GetPullRequestComments = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetPullRequestComments',
                request_serializer=github__pb2.GetPullRequestCommentsRequest.SerializeToString,
                response_deserializer=github__pb2.GetPullRequestCommentsResponse.FromString,
                _registered_method=True)
        self.GetPullRequestReviews = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/GetPullRequestReviews',
                request_serializer=github__pb2.GetPullRequestReviewsRequest.SerializeToString,
                response_deserializer=github__pb2.GetPullRequestReviewsResponse.FromString,
                _registered_method=True)
        self.SearchCode = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/SearchCode',
                request_serializer=github__pb2.SearchCodeRequest.SerializeToString,
                response_deserializer=github__pb2.SearchCodeResponse.FromString,
                _registered_method=True)
        self.SearchUsers = channel.unary_unary(
                '/tucker.mcproto.github.v1.GitHubService/SearchUsers',
                request_serializer=github__pb2.SearchUsersRequest.SerializeToString,
                response_deserializer=github__pb2.SearchUsersResponse.FromString,
                _registered_method=True)


class GitHubServiceServicer(object):
    """Service definition for GitHub MCP
    """

    def CreateRepository(self, request, context):
        """Repository Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchRepositories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRepository(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForkRepository(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileContents(self, request, context):
        """File Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrUpdateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBranch(self, request, context):
        """Branch & Commit Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCommits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateIssue(self, request, context):
        """Issue Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIssues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIssue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddIssueComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchIssues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePullRequest(self, request, context):
        """Pull Request Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPullRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPullRequests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePullRequestReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergePullRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPullRequestFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPullRequestStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePullRequestBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPullRequestComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPullRequestReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCode(self, request, context):
        """Search & User Operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GitHubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRepository,
                    request_deserializer=github__pb2.CreateRepositoryRequest.FromString,
                    response_serializer=github__pb2.CreateRepositoryResponse.SerializeToString,
            ),
            'SearchRepositories': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchRepositories,
                    request_deserializer=github__pb2.SearchRepositoriesRequest.FromString,
                    response_serializer=github__pb2.SearchRepositoriesResponse.SerializeToString,
            ),
            'GetRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepository,
                    request_deserializer=github__pb2.GetRepositoryRequest.FromString,
                    response_serializer=github__pb2.GetRepositoryResponse.SerializeToString,
            ),
            'ForkRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.ForkRepository,
                    request_deserializer=github__pb2.ForkRepositoryRequest.FromString,
                    response_serializer=github__pb2.ForkRepositoryResponse.SerializeToString,
            ),
            'GetFileContents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileContents,
                    request_deserializer=github__pb2.GetFileContentsRequest.FromString,
                    response_serializer=github__pb2.GetFileContentsResponse.SerializeToString,
            ),
            'CreateOrUpdateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrUpdateFile,
                    request_deserializer=github__pb2.CreateOrUpdateFileRequest.FromString,
                    response_serializer=github__pb2.FileCommitResponse.SerializeToString,
            ),
            'PushFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.PushFiles,
                    request_deserializer=github__pb2.PushFilesRequest.FromString,
                    response_serializer=github__pb2.PushFilesResponse.SerializeToString,
            ),
            'CreateBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBranch,
                    request_deserializer=github__pb2.CreateBranchRequest.FromString,
                    response_serializer=github__pb2.CreateBranchResponse.SerializeToString,
            ),
            'ListCommits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCommits,
                    request_deserializer=github__pb2.ListCommitsRequest.FromString,
                    response_serializer=github__pb2.ListCommitsResponse.SerializeToString,
            ),
            'CreateIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIssue,
                    request_deserializer=github__pb2.CreateIssueRequest.FromString,
                    response_serializer=github__pb2.CreateIssueResponse.SerializeToString,
            ),
            'ListIssues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIssues,
                    request_deserializer=github__pb2.ListIssuesRequest.FromString,
                    response_serializer=github__pb2.ListIssuesResponse.SerializeToString,
            ),
            'GetIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIssue,
                    request_deserializer=github__pb2.GetIssueRequest.FromString,
                    response_serializer=github__pb2.GetIssueResponse.SerializeToString,
            ),
            'UpdateIssue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIssue,
                    request_deserializer=github__pb2.UpdateIssueRequest.FromString,
                    response_serializer=github__pb2.UpdateIssueResponse.SerializeToString,
            ),
            'AddIssueComment': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIssueComment,
                    request_deserializer=github__pb2.AddIssueCommentRequest.FromString,
                    response_serializer=github__pb2.AddIssueCommentResponse.SerializeToString,
            ),
            'SearchIssues': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchIssues,
                    request_deserializer=github__pb2.SearchIssuesRequest.FromString,
                    response_serializer=github__pb2.SearchIssuesResponse.SerializeToString,
            ),
            'CreatePullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePullRequest,
                    request_deserializer=github__pb2.CreatePullRequestRequest.FromString,
                    response_serializer=github__pb2.CreatePullRequestResponse.SerializeToString,
            ),
            'GetPullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPullRequest,
                    request_deserializer=github__pb2.GetPullRequestRequest.FromString,
                    response_serializer=github__pb2.GetPullRequestResponse.SerializeToString,
            ),
            'ListPullRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPullRequests,
                    request_deserializer=github__pb2.ListPullRequestsRequest.FromString,
                    response_serializer=github__pb2.ListPullRequestsResponse.SerializeToString,
            ),
            'CreatePullRequestReview': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePullRequestReview,
                    request_deserializer=github__pb2.CreatePullRequestReviewRequest.FromString,
                    response_serializer=github__pb2.CreatePullRequestReviewResponse.SerializeToString,
            ),
            'MergePullRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MergePullRequest,
                    request_deserializer=github__pb2.MergePullRequestRequest.FromString,
                    response_serializer=github__pb2.MergePullRequestResponse.SerializeToString,
            ),
            'GetPullRequestFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPullRequestFiles,
                    request_deserializer=github__pb2.GetPullRequestFilesRequest.FromString,
                    response_serializer=github__pb2.GetPullRequestFilesResponse.SerializeToString,
            ),
            'GetPullRequestStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPullRequestStatus,
                    request_deserializer=github__pb2.GetPullRequestStatusRequest.FromString,
                    response_serializer=github__pb2.GetPullRequestStatusResponse.SerializeToString,
            ),
            'UpdatePullRequestBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePullRequestBranch,
                    request_deserializer=github__pb2.UpdatePullRequestBranchRequest.FromString,
                    response_serializer=github__pb2.UpdatePullRequestBranchResponse.SerializeToString,
            ),
            'GetPullRequestComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPullRequestComments,
                    request_deserializer=github__pb2.GetPullRequestCommentsRequest.FromString,
                    response_serializer=github__pb2.GetPullRequestCommentsResponse.SerializeToString,
            ),
            'GetPullRequestReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPullRequestReviews,
                    request_deserializer=github__pb2.GetPullRequestReviewsRequest.FromString,
                    response_serializer=github__pb2.GetPullRequestReviewsResponse.SerializeToString,
            ),
            'SearchCode': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCode,
                    request_deserializer=github__pb2.SearchCodeRequest.FromString,
                    response_serializer=github__pb2.SearchCodeResponse.SerializeToString,
            ),
            'SearchUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUsers,
                    request_deserializer=github__pb2.SearchUsersRequest.FromString,
                    response_serializer=github__pb2.SearchUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tucker.mcproto.github.v1.GitHubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tucker.mcproto.github.v1.GitHubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GitHubService(object):
    """Service definition for GitHub MCP
    """

    @staticmethod
    def CreateRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/CreateRepository',
            github__pb2.CreateRepositoryRequest.SerializeToString,
            github__pb2.CreateRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchRepositories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/SearchRepositories',
            github__pb2.SearchRepositoriesRequest.SerializeToString,
            github__pb2.SearchRepositoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetRepository',
            github__pb2.GetRepositoryRequest.SerializeToString,
            github__pb2.GetRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForkRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/ForkRepository',
            github__pb2.ForkRepositoryRequest.SerializeToString,
            github__pb2.ForkRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileContents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetFileContents',
            github__pb2.GetFileContentsRequest.SerializeToString,
            github__pb2.GetFileContentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrUpdateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/CreateOrUpdateFile',
            github__pb2.CreateOrUpdateFileRequest.SerializeToString,
            github__pb2.FileCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/PushFiles',
            github__pb2.PushFilesRequest.SerializeToString,
            github__pb2.PushFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/CreateBranch',
            github__pb2.CreateBranchRequest.SerializeToString,
            github__pb2.CreateBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCommits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/ListCommits',
            github__pb2.ListCommitsRequest.SerializeToString,
            github__pb2.ListCommitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/CreateIssue',
            github__pb2.CreateIssueRequest.SerializeToString,
            github__pb2.CreateIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIssues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/ListIssues',
            github__pb2.ListIssuesRequest.SerializeToString,
            github__pb2.ListIssuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetIssue',
            github__pb2.GetIssueRequest.SerializeToString,
            github__pb2.GetIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIssue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/UpdateIssue',
            github__pb2.UpdateIssueRequest.SerializeToString,
            github__pb2.UpdateIssueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddIssueComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/AddIssueComment',
            github__pb2.AddIssueCommentRequest.SerializeToString,
            github__pb2.AddIssueCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchIssues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/SearchIssues',
            github__pb2.SearchIssuesRequest.SerializeToString,
            github__pb2.SearchIssuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/CreatePullRequest',
            github__pb2.CreatePullRequestRequest.SerializeToString,
            github__pb2.CreatePullRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetPullRequest',
            github__pb2.GetPullRequestRequest.SerializeToString,
            github__pb2.GetPullRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPullRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/ListPullRequests',
            github__pb2.ListPullRequestsRequest.SerializeToString,
            github__pb2.ListPullRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePullRequestReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/CreatePullRequestReview',
            github__pb2.CreatePullRequestReviewRequest.SerializeToString,
            github__pb2.CreatePullRequestReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergePullRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/MergePullRequest',
            github__pb2.MergePullRequestRequest.SerializeToString,
            github__pb2.MergePullRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPullRequestFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetPullRequestFiles',
            github__pb2.GetPullRequestFilesRequest.SerializeToString,
            github__pb2.GetPullRequestFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPullRequestStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetPullRequestStatus',
            github__pb2.GetPullRequestStatusRequest.SerializeToString,
            github__pb2.GetPullRequestStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePullRequestBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/UpdatePullRequestBranch',
            github__pb2.UpdatePullRequestBranchRequest.SerializeToString,
            github__pb2.UpdatePullRequestBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPullRequestComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetPullRequestComments',
            github__pb2.GetPullRequestCommentsRequest.SerializeToString,
            github__pb2.GetPullRequestCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPullRequestReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/GetPullRequestReviews',
            github__pb2.GetPullRequestReviewsRequest.SerializeToString,
            github__pb2.GetPullRequestReviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/SearchCode',
            github__pb2.SearchCodeRequest.SerializeToString,
            github__pb2.SearchCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tucker.mcproto.github.v1.GitHubService/SearchUsers',
            github__pb2.SearchUsersRequest.SerializeToString,
            github__pb2.SearchUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
