"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import mcp_pb2 as _mcp_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class MCPServiceStub:
    """Service definition for network transports (gRPC)"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> MCPServiceAsyncStub: ...
    Initialize: _grpc.UnaryUnaryMultiCallable[_mcp_pb2.InitializeRequest, _mcp_pb2.InitializeResponse]
    ListTools: _grpc.UnaryUnaryMultiCallable[_mcp_pb2.ListToolsRequest, _mcp_pb2.ListToolsResponse]
    CallTool: _grpc.UnaryUnaryMultiCallable[_mcp_pb2.CallToolRequest, _mcp_pb2.CallToolResponse]
    ListResources: _grpc.UnaryUnaryMultiCallable[_mcp_pb2.ListResourcesRequest, _mcp_pb2.ListResourcesResponse]
    ReadResource: _grpc.UnaryUnaryMultiCallable[_mcp_pb2.ReadResourceRequest, _mcp_pb2.ReadResourceResponse]

@_typing.type_check_only
class MCPServiceAsyncStub(MCPServiceStub):
    """Service definition for network transports (gRPC)"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    Initialize: _aio.UnaryUnaryMultiCallable[_mcp_pb2.InitializeRequest, _mcp_pb2.InitializeResponse]  # type: ignore[assignment]
    ListTools: _aio.UnaryUnaryMultiCallable[_mcp_pb2.ListToolsRequest, _mcp_pb2.ListToolsResponse]  # type: ignore[assignment]
    CallTool: _aio.UnaryUnaryMultiCallable[_mcp_pb2.CallToolRequest, _mcp_pb2.CallToolResponse]  # type: ignore[assignment]
    ListResources: _aio.UnaryUnaryMultiCallable[_mcp_pb2.ListResourcesRequest, _mcp_pb2.ListResourcesResponse]  # type: ignore[assignment]
    ReadResource: _aio.UnaryUnaryMultiCallable[_mcp_pb2.ReadResourceRequest, _mcp_pb2.ReadResourceResponse]  # type: ignore[assignment]

class MCPServiceServicer(metaclass=_abc_1.ABCMeta):
    """Service definition for network transports (gRPC)"""

    @_abc_1.abstractmethod
    def Initialize(
        self,
        request: _mcp_pb2.InitializeRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mcp_pb2.InitializeResponse, _abc.Awaitable[_mcp_pb2.InitializeResponse]]: ...

    @_abc_1.abstractmethod
    def ListTools(
        self,
        request: _mcp_pb2.ListToolsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mcp_pb2.ListToolsResponse, _abc.Awaitable[_mcp_pb2.ListToolsResponse]]: ...

    @_abc_1.abstractmethod
    def CallTool(
        self,
        request: _mcp_pb2.CallToolRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mcp_pb2.CallToolResponse, _abc.Awaitable[_mcp_pb2.CallToolResponse]]: ...

    @_abc_1.abstractmethod
    def ListResources(
        self,
        request: _mcp_pb2.ListResourcesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mcp_pb2.ListResourcesResponse, _abc.Awaitable[_mcp_pb2.ListResourcesResponse]]: ...

    @_abc_1.abstractmethod
    def ReadResource(
        self,
        request: _mcp_pb2.ReadResourceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_mcp_pb2.ReadResourceResponse, _abc.Awaitable[_mcp_pb2.ReadResourceResponse]]: ...

def add_MCPServiceServicer_to_server(servicer: MCPServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
