// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A generic data event in the pipeline
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain    string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"` // e.g., "marketing", "auth", "billing"
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The actual variable payload
	Payload       *structpb.Struct `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Extraction Request
type ExtractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	Filters       map[string]string      `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ExtractRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ExtractRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// Transformation/Mapping Rule
type TransformRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Event         *Event                   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Rules         []*TransformRequest_Rule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest) Reset() {
	*x = TransformRequest{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest) ProtoMessage() {}

func (x *TransformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest.ProtoReflect.Descriptor instead.
func (*TransformRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *TransformRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TransformRequest) GetRules() []*TransformRequest_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// Loading/Sink Request
type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetBucket  string                 `protobuf:"bytes,1,opt,name=target_bucket,json=targetBucket,proto3" json:"target_bucket,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Overwrite     bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *LoadRequest) GetTargetBucket() string {
	if x != nil {
		return x.TargetBucket
	}
	return ""
}

func (x *LoadRequest) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *LoadRequest) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

type LoadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedCount int32                  `protobuf:"varint,1,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoadResponse) Reset() {
	*x = LoadResponse{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadResponse) ProtoMessage() {}

func (x *LoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadResponse.ProtoReflect.Descriptor instead.
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *LoadResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *LoadResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// A complex rule set showing nested schema overhead
type TransformRequest_Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetField   string                 `protobuf:"bytes,1,opt,name=target_field,json=targetField,proto3" json:"target_field,omitempty"`
	TransformOp   string                 `protobuf:"bytes,2,opt,name=transform_op,json=transformOp,proto3" json:"transform_op,omitempty"` // e.g., "uppercase", "hash", "mask"
	FallbackValue string                 `protobuf:"bytes,3,opt,name=fallback_value,json=fallbackValue,proto3" json:"fallback_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRequest_Rule) Reset() {
	*x = TransformRequest_Rule{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRequest_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRequest_Rule) ProtoMessage() {}

func (x *TransformRequest_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRequest_Rule.ProtoReflect.Descriptor instead.
func (*TransformRequest_Rule) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TransformRequest_Rule) GetTargetField() string {
	if x != nil {
		return x.TargetField
	}
	return ""
}

func (x *TransformRequest_Rule) GetTransformOp() string {
	if x != nil {
		return x.TransformOp
	}
	return ""
}

func (x *TransformRequest_Rule) GetFallbackValue() string {
	if x != nil {
		return x.FallbackValue
	}
	return ""
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\x13misfit.analytics.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x9c\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\"\xd4\x01\n" +
	"\x0eExtractRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\x12J\n" +
	"\afilters\x18\x03 \x03(\v20.misfit.analytics.v1.ExtractRequest.FiltersEntryR\afilters\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\x10TransformRequest\x120\n" +
	"\x05event\x18\x01 \x01(\v2\x1a.misfit.analytics.v1.EventR\x05event\x12@\n" +
	"\x05rules\x18\x02 \x03(\v2*.misfit.analytics.v1.TransformRequest.RuleR\x05rules\x1as\n" +
	"\x04Rule\x12!\n" +
	"\ftarget_field\x18\x01 \x01(\tR\vtargetField\x12!\n" +
	"\ftransform_op\x18\x02 \x01(\tR\vtransformOp\x12%\n" +
	"\x0efallback_value\x18\x03 \x01(\tR\rfallbackValue\"\x84\x01\n" +
	"\vLoadRequest\x12#\n" +
	"\rtarget_bucket\x18\x01 \x01(\tR\ftargetBucket\x122\n" +
	"\x06events\x18\x02 \x03(\v2\x1a.misfit.analytics.v1.EventR\x06events\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\"O\n" +
	"\fLoadResponse\x12'\n" +
	"\x0fprocessed_count\x18\x01 \x01(\x05R\x0eprocessedCount\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xfd\x01\n" +
	"\x10AnalyticsService\x12L\n" +
	"\aExtract\x12#.misfit.analytics.v1.ExtractRequest\x1a\x1a.misfit.analytics.v1.Event0\x01\x12N\n" +
	"\tTransform\x12%.misfit.analytics.v1.TransformRequest\x1a\x1a.misfit.analytics.v1.Event\x12K\n" +
	"\x04Load\x12 .misfit.analytics.v1.LoadRequest\x1a!.misfit.analytics.v1.LoadResponseB1Z/github.com/misfitdev/proto-mcp/go/pkg/analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_analytics_proto_goTypes = []any{
	(*Event)(nil),                 // 0: misfit.analytics.v1.Event
	(*ExtractRequest)(nil),        // 1: misfit.analytics.v1.ExtractRequest
	(*TransformRequest)(nil),      // 2: misfit.analytics.v1.TransformRequest
	(*LoadRequest)(nil),           // 3: misfit.analytics.v1.LoadRequest
	(*LoadResponse)(nil),          // 4: misfit.analytics.v1.LoadResponse
	nil,                           // 5: misfit.analytics.v1.ExtractRequest.FiltersEntry
	(*TransformRequest_Rule)(nil), // 6: misfit.analytics.v1.TransformRequest.Rule
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 8: google.protobuf.Struct
}
var file_analytics_proto_depIdxs = []int32{
	7, // 0: misfit.analytics.v1.Event.timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: misfit.analytics.v1.Event.payload:type_name -> google.protobuf.Struct
	5, // 2: misfit.analytics.v1.ExtractRequest.filters:type_name -> misfit.analytics.v1.ExtractRequest.FiltersEntry
	0, // 3: misfit.analytics.v1.TransformRequest.event:type_name -> misfit.analytics.v1.Event
	6, // 4: misfit.analytics.v1.TransformRequest.rules:type_name -> misfit.analytics.v1.TransformRequest.Rule
	0, // 5: misfit.analytics.v1.LoadRequest.events:type_name -> misfit.analytics.v1.Event
	1, // 6: misfit.analytics.v1.AnalyticsService.Extract:input_type -> misfit.analytics.v1.ExtractRequest
	2, // 7: misfit.analytics.v1.AnalyticsService.Transform:input_type -> misfit.analytics.v1.TransformRequest
	3, // 8: misfit.analytics.v1.AnalyticsService.Load:input_type -> misfit.analytics.v1.LoadRequest
	0, // 9: misfit.analytics.v1.AnalyticsService.Extract:output_type -> misfit.analytics.v1.Event
	0, // 10: misfit.analytics.v1.AnalyticsService.Transform:output_type -> misfit.analytics.v1.Event
	4, // 11: misfit.analytics.v1.AnalyticsService.Load:output_type -> misfit.analytics.v1.LoadResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
